var $jscomp={scope:{},checkStringArgs:function(n,w,f){if(null==n)throw new TypeError("The 'this' value for String.prototype."+f+" must not be null or undefined");if(w instanceof RegExp)throw new TypeError("First argument to String.prototype."+f+" must not be a regular expression");return n+""}};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(n,w,f){if(f.get||f.set)throw new TypeError("ES3 does not support getters and setters.");n!=Array.prototype&&n!=Object.prototype&&(n[w]=f.value)};$jscomp.getGlobal=function(n){return"undefined"!=typeof window&&window===n?n:"undefined"!=typeof global?global:n};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(n,w,f,l){if(w){f=$jscomp.global;n=n.split(".");for(l=0;l<n.length-1;l++){var Q=n[l];Q in f||(f[Q]={});f=f[Q]}n=n[n.length-1];l=f[n];w=w(l);w!=l&&null!=w&&$jscomp.defineProperty(f,n,{configurable:!0,writable:!0,value:w})}};
$jscomp.polyfill("String.prototype.endsWith",function(n){return n?n:function(n,f){var l=$jscomp.checkStringArgs(this,n,"endsWith");n+="";void 0===f&&(f=l.length);f=Math.max(0,Math.min(f|0,l.length));for(var w=n.length;0<w&&0<f;)if(l[--f]!=n[--w])return!1;return 0>=w}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.startsWith",function(n){return n?n:function(n,f){var l=$jscomp.checkStringArgs(this,n,"startsWith");n+="";var w=l.length,D=n.length;f=Math.max(0,Math.min(f|0,l.length));for(var S=0;S<D&&f<w;)if(l[f++]!=n[S++])return!1;return S>=D}},"es6-impl","es3");
$jscomp.polyfill("String.prototype.repeat",function(n){return n?n:function(n){var f=$jscomp.checkStringArgs(this,null,"repeat");if(0>n||1342177279<n)throw new RangeError("Invalid count value");n|=0;for(var l="";n;)if(n&1&&(l+=f),n>>>=1)f+=f;return l}},"es6-impl","es3");$jscomp.owns=function(n,w){return Object.prototype.hasOwnProperty.call(n,w)};
$jscomp.polyfill("Object.assign",function(n){return n?n:function(n,f){for(var l=1;l<arguments.length;l++){var w=arguments[l];if(w)for(var D in w)$jscomp.owns(w,D)&&(n[D]=w[D])}return n}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(n){return $jscomp.SYMBOL_PREFIX+(n||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var n=$jscomp.global.Symbol.iterator;n||(n=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[n]&&$jscomp.defineProperty(Array.prototype,n,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(n){var w=0;return $jscomp.iteratorPrototype(function(){return w<n.length?{done:!1,value:n[w++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(n){$jscomp.initSymbolIterator();n={next:n};n[$jscomp.global.Symbol.iterator]=function(){return this};return n};$jscomp.array=$jscomp.array||{};$jscomp.iteratorFromArray=function(n,w){$jscomp.initSymbolIterator();n instanceof String&&(n+="");var f=0,l={next:function(){if(f<n.length){var Q=f++;return{value:w(Q,n[Q]),done:!1}}l.next=function(){return{done:!0,value:void 0}};return l.next()}};l[Symbol.iterator]=function(){return l};return l};
$jscomp.polyfill("Array.prototype.keys",function(n){return n?n:function(){return $jscomp.iteratorFromArray(this,function(n){return n})}},"es6-impl","es3");
(function(n){function w(l){if(f[l])return f[l].exports;var Q=f[l]={exports:{},id:l,loaded:!1};n[l].call(Q.exports,Q,Q.exports,w);Q.loaded=!0;return Q.exports}var f={};w.m=n;w.c=f;w.p="";return w(0)})([function(n,w,f){f(1);f(2).Main.fullscreen()},function(n,w,f){n.exports=f.p+"index.html"},function(n,w){(function(){function f(a){function b(b){return function(c){return a(b,c)}}b.arity=2;b.func=a;return b}function l(a){function b(b){return function(c){return function(d){return a(b,c,d)}}}b.arity=3;b.func=
a;return b}function w(a){function b(b){return function(c){return function(d){return function(g){return a(b,c,d,g)}}}}b.arity=4;b.func=a;return b}function D(a){function b(b){return function(c){return function(d){return function(g){return function(e){return a(b,c,d,g,e)}}}}}b.arity=5;b.func=a;return b}function S(a){function b(b){return function(c){return function(d){return function(g){return function(e){return function(ga){return a(b,c,d,g,e,ga)}}}}}}b.arity=6;b.func=a;return b}function rb(a){function b(b){return function(c){return function(d){return function(g){return function(e){return function(ga){return function(f){return a(b,
c,d,g,e,ga,f)}}}}}}}b.arity=7;b.func=a;return b}function sb(a){function b(b){return function(c){return function(d){return function(g){return function(e){return function(ga){return function(f){return function(T){return a(b,c,d,g,e,ga,f,T)}}}}}}}}b.arity=8;b.func=a;return b}function tb(a){function b(b){return function(c){return function(d){return function(g){return function(e){return function(ga){return function(f){return function(T){return function(k){return a(b,c,d,g,e,ga,f,T,k)}}}}}}}}}b.arity=9;
b.func=a;return b}function e(a,b,c){return 2===a.arity?a.func(b,c):a(b)(c)}function p(a,b,c,d){return 3===a.arity?a.func(b,c,d):a(b)(c)(d)}function aa(a,b,c,d,g){return 4===a.arity?a.func(b,c,d,g):a(b)(c)(d)(g)}function v(a,b,c,d,g,e){return 5===a.arity?a.func(b,c,d,g,e):a(b)(c)(d)(g)(e)}function ub(a,b,c,d,g,e,f){return 6===a.arity?a.func(b,c,d,g,e,f):a(b)(c)(d)(g)(e)(f)}var I=function(){function a(b,d){if(0===d)throw Error("Cannot perform mod 0. Division by zero error.");var c=b%d;b=0===b?0:0<d?
0<=b?c:c+d:-a(-b,-d);return b===d?0:b}var b=["LT","EQ","GT"];return{div:f(function(a,b){return a/b|0}),rem:f(function(a,b){return a%b}),mod:f(a),pi:Math.PI,e:Math.E,cos:Math.cos,sin:Math.sin,tan:Math.tan,acos:Math.acos,asin:Math.asin,atan:Math.atan,atan2:f(Math.atan2),degrees:function(a){return a*Math.PI/180},turns:function(a){return 2*Math.PI*a},fromPolar:function(a){var b=a._0;a=a._1;return q.Tuple2(b*Math.cos(a),b*Math.sin(a))},toPolar:function(a){var b=a._0;a=a._1;return q.Tuple2(Math.sqrt(b*
b+a*a),Math.atan2(a,b))},sqrt:Math.sqrt,logBase:f(function(a,b){return Math.log(b)/Math.log(a)}),negate:function(a){return-a},abs:function(a){return 0>a?-a:a},min:f(function(a,b){return 0>q.cmp(a,b)?a:b}),max:f(function(a,b){return 0<q.cmp(a,b)?a:b}),clamp:l(function(a,b,g){return 0>q.cmp(g,a)?a:0<q.cmp(g,b)?b:g}),compare:f(function(a,d){return{ctor:b[q.cmp(a,d)+1]}}),xor:f(function(a,b){return a!==b}),not:function(a){return!a},truncate:function(a){return a|0},ceiling:Math.ceil,floor:Math.floor,round:Math.round,
toFloat:function(a){return a},isNaN:isNaN,isInfinite:function(a){return Infinity===a||-Infinity===a}}}(),q=function(){function a(b,c,d,k){if(100<d)return k.push({x:b,y:c}),!0;if(b===c)return!0;if("object"!==typeof b){if("function"===typeof b)throw Error('Trying to use `(==)` on functions. There is no way to know if functions are "the same" in the Elm sense. Read more about this at http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#== which describes why it is this way and what the better version will look like.');
return!1}if(null===b||null===c)return!1;if(b instanceof Date)return b.getTime()===c.getTime();if(!("ctor"in b)){for(var g in b)if(!a(b[g],c[g],d+1,k))return!1;return!0}if("RBNode_elm_builtin"===b.ctor||"RBEmpty_elm_builtin"===b.ctor)b=Ea(b),c=Ea(c);"Set_elm_builtin"===b.ctor&&(b=_elm_lang$core$Set$toList(b),c=_elm_lang$core$Set$toList(c));if("::"===b.ctor){for(;"::"===b.ctor&&"::"===c.ctor;){if(!a(b._0,c._0,d+1,k))return!1;b=b._1;c=c._1}return b.ctor===c.ctor}if("_Array"===b.ctor){b=E.toJSArray(b);
c=E.toJSArray(c);if(b.length!==c.length)return!1;for(g=0;g<b.length;g++)if(!a(b[g],c[g],d+1,k))return!1;return!0}if(!a(b.ctor,c.ctor,d+1,k))return!1;for(g in b)if(!a(b[g],c[g],d+1,k))return!1;return!0}function b(a,c){if("object"!==typeof a)return a===c?0:a<c?-1:1;if(a instanceof String)return a=a.valueOf(),c=c.valueOf(),a===c?0:a<c?-1:1;if("::"===a.ctor||"[]"===a.ctor){for(;"::"===a.ctor&&"::"===c.ctor;){var d=b(a._0,c._0);if(0!==d)return d;a=a._1;c=c._1}return a.ctor===c.ctor?0:"[]"===a.ctor?-1:
1}if("_Tuple"===a.ctor.slice(0,6)){var k=a.ctor.slice(6)-0;if(0===k)return 0;if(1<=k){d=b(a._0,c._0);if(0!==d)return d;if(2<=k){d=b(a._1,c._1);if(0!==d)return d;if(3<=k){d=b(a._2,c._2);if(0!==d)return d;if(4<=k){d=b(a._3,c._3);if(0!==d)return d;if(5<=k){d=b(a._4,c._4);if(0!==d)return d;if(6<=k){d=b(a._5,c._5);if(0!==d)return d;if(7<=k)throw Error("Comparison error: cannot compare tuples with more than 6 elements.");}}}}}}return 0}throw Error("Comparison error: comparison is only defined on ints, floats, times, chars, strings, lists of comparable values, and tuples of comparable values.");
}function c(a){return a.start.line==a.end.line?"on line "+a.start.line:"between lines "+a.start.line+" and "+a.end.line}function d(a){var b=typeof a;if("function"===b)return a=a.func?a.func.name:a.name,"<function"+(""===a?"":":")+a+">";if("boolean"===b)return a?"True":"False";if("number"===b)return a+"";if(a instanceof String)return"'"+g(a,!0)+"'";if("string"===b)return'"'+g(a,!1)+'"';if(null===a)return"null";if("object"===b&&"ctor"in a){b=a.ctor.substring(0,5);if("_Tupl"===b){var b=[],c;for(c in a)"ctor"!==
c&&b.push(d(a[c]));return"("+b.join(",")+")"}if("_Task"===b)return"<task>";if("_Array"===a.ctor)return a=ha(a),"Array.fromList "+d(a);if("<decoder>"===a.ctor)return"<decoder>";if("_Process"===a.ctor)return"<process:"+a.id+">";if("::"===a.ctor){b="["+d(a._0);for(a=a._1;"::"===a.ctor;)b+=","+d(a._0),a=a._1;return b+"]"}if("[]"===a.ctor)return"[]";if("Set_elm_builtin"===a.ctor)return"Set.fromList "+d(_elm_lang$core$Set$toList(a));if("RBNode_elm_builtin"===a.ctor||"RBEmpty_elm_builtin"===a.ctor)return"Dict.fromList "+
d(Ea(a));var b="",k;for(k in a)if("ctor"!==k){c=d(a[k]);var e=c[0],e="{"===e||"("===e||"<"===e||'"'===e||0>c.indexOf(" "),b=b+(" "+(e?c:"("+c+")"))}return a.ctor+b}if("object"===b){if(a instanceof Date)return"<"+a.toString()+">";if(a.elm_web_socket)return"<websocket>";b=[];for(c in a)b.push(c+" = "+d(a[c]));return 0===b.length?"{}":"{ "+b.join(", ")+" }"}return"<internal structure>"}function g(a,b){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/\t/g,"\\t").replace(/\r/g,"\\r").replace(/\v/g,
"\\v").replace(/\0/g,"\\0");return b?a.replace(/\'/g,"\\'"):a.replace(/\"/g,'\\"')}var e=0,h={ctor:"[]"};return{eq:function(b,c){var d=[];b=a(b,c,0,d);for(var k;b&&(k=d.pop());)b=a(k.x,k.y,0,d);return b},cmp:b,Tuple0:{ctor:"_Tuple0"},Tuple2:function(a,b){return{ctor:"_Tuple2",_0:a,_1:b}},chr:function(a){return new String(a)},update:function(a,b){var c={},d;for(d in a)c[d]=d in b?b[d]:a[d];return c},guid:function(a){return e++},append:f(function(a,b){if("string"===typeof a)return a+b;if("[]"===a.ctor)return b;
var c={ctor:"::",_0:a._0,_1:h},d=c;for(a=a._1;"[]"!==a.ctor;)d._1={ctor:"::",_0:a._0,_1:h},a=a._1,d=d._1;d._1=b;return c}),crash:function(a,b){return function(d){throw Error("Ran into a `Debug.crash` in module `"+a+"` "+c(b)+"\nThe message provided by the code author is:\n\n    "+d);}},crashCase:function(a,b,g){return function(k){throw Error("Ran into a `Debug.crash` in module `"+a+"`\n\nThis was caused by the `case` expression "+c(b)+".\nOne of the branches ended with a crash and the following value got through:\n\n    "+
d(g)+"\n\nThe message provided by the code author is:\n\n    "+k);}},toString:d}}();f(function(a,b){return e(a,b._0,b._1)});l(function(a,b,c){return a({ctor:"_Tuple2",_0:b,_1:c})});l(function(a,b,c){return e(a,c,b)});var Ta=f(function(a,b){return a}),r=r||{};r["<|"]=f(function(a,b){return a(b)});r=r||{};r["|>"]=f(function(a,b){return b(a)});r=r||{};r[">>"]=l(function(a,b,c){return b(a(c))});r=r||{};r["<<"]=l(function(a,b,c){return a(b(c))});r=r||{};r["++"]=q.append;var ea=q.toString,qa=I.not,r=r||
{};r["||"]=I.or;r=r||{};r["&&"]=I.and;var oc=I.min,vb=I.compare,r=r||{};r[">="]=I.ge;r=r||{};r["<="]=I.le;r=r||{};r[">"]=I.gt;r=r||{};r["<"]=I.lt;r=r||{};r["/="]=I.neq;r=r||{};r["=="]=I.eq;r=r||{};r["^"]=I.exp;r=r||{};r["%"]=I.mod;r=r||{};r["//"]=I.div;r=r||{};r["/"]=I.floatDiv;r=r||{};r["*"]=I.mul;r=r||{};r["-"]=I.sub;r=r||{};r["+"]=I.add;var ra=function(){return{crash:function(a){throw Error(a);},log:f(function(a,b){a=a+": "+q.toString(b);var c=c||{};c.stdout?c.stdout.write(a):console.log(a);return b})}}();
f(function(a,b){return"Just"===b.ctor?b._0:a});var J={ctor:"Nothing"};f(function(a,b){return"Just"===a.ctor?b(a._0):J});var L=function(a){return{ctor:"Just",_0:a}};f(function(a,b){return"Just"===b.ctor?L(a(b._0)):J});l(function(a,b,c){return"Just"===b.ctor&&"Just"===c.ctor?L(e(a,b._0,c._0)):J});w(function(a,b,c,d){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor?L(p(a,b._0,c._0,d._0)):J});D(function(a,b,c,d,g){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===g.ctor?L(aa(a,
b._0,c._0,d._0,g._0)):J});S(function(a,b,c,d,g,e){return"Just"===b.ctor&&"Just"===c.ctor&&"Just"===d.ctor&&"Just"===g.ctor&&"Just"===e.ctor?L(v(a,b._0,c._0,d._0,g._0,e._0)):J});var h=function(){function a(a,b){return{ctor:"::",_0:a,_1:b}}function b(b){for(var c=d,g=b.length;g--;)c=a(b[g],c);return c}function c(a){for(var b=[];"[]"!==a.ctor;)b.push(a._0),a=a._1;return b}var d={ctor:"[]"};return{Nil:d,Cons:a,cons:f(a),toArray:c,fromArray:b,range:function(b,c){var e=d;if(b<=c){do e=a(c,e);while(c-- >
b)}return e},foldr:l(function(a,b,d){d=c(d);for(var g=d.length;g--;)b=e(a,d[g],b);return b}),map2:l(function(a,c,d){for(var g=[];"[]"!==c.ctor&&"[]"!==d.ctor;)g.push(e(a,c._0,d._0)),c=c._1,d=d._1;return b(g)}),map3:w(function(a,c,d,e){for(var g=[];"[]"!==c.ctor&&"[]"!==d.ctor&&"[]"!==e.ctor;)g.push(p(a,c._0,d._0,e._0)),c=c._1,d=d._1,e=e._1;return b(g)}),map4:D(function(a,c,d,e,f){for(var g=[];"[]"!==c.ctor&&"[]"!==d.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor;)g.push(aa(a,c._0,d._0,e._0,f._0)),c=c._1,d=d._1,
e=e._1,f=f._1;return b(g)}),map5:S(function(a,c,d,e,f,h){for(var k=[];"[]"!==c.ctor&&"[]"!==d.ctor&&"[]"!==e.ctor&&"[]"!==f.ctor&&"[]"!==h.ctor;)k.push(v(a,c._0,d._0,e._0,f._0,h._0)),c=c._1,d=d._1,e=e._1,f=f._1,h=h._1;return b(k)}),sortBy:f(function(a,d){return b(c(d).sort(function(b,c){return q.cmp(a(b),a(c))}))}),sortWith:f(function(a,d){return b(c(d).sort(function(b,c){b=a(b)(c).ctor;return"EQ"===b?0:"LT"===b?-1:1}))})}}(),pc=h.sortBy;f(function(a,b){for(;;){if(1>q.cmp(a,0))return b;var c=b;if("[]"===
c.ctor)return b;b=c._1;--a}});var qc=h.map2,la=f(function(a,b){for(;;){if("[]"===b.ctor)return!1;if(a(b._0))return!0;b=b._1}});f(function(a,b){return qa(e(la,function(b){return qa(a(b))},b))});var fa=h.foldr,sa=l(function(a,b,c){for(;;){var d=c;if("[]"===d.ctor)return b;c=a;b=e(a,d._0,b);d=d._1;a=c;c=d}}),Ua=function(a){return p(sa,f(function(a,c){return c+1}),0,a)};f(function(a,b){return p(qc,a,h.range(0,Ua(b)-1),b)});var rc=f(function(a,b){return e(la,function(b){return q.eq(b,a)},b)}),sc=function(a){return"::"===
a.ctor?L(a._0):J},y=y||{};y["::"]=h.cons;var ia=f(function(a,b){return p(fa,f(function(b,d){return e(y["::"],a(b),d)}),h.fromArray([]),b)}),Fa=f(function(a,b){var c=f(function(b,c){return a(b)?e(y["::"],b,c):c});return p(fa,c,h.fromArray([]),b)}),tc=l(function(a,b,c){a=a(b);return"Just"===a.ctor?e(y["::"],a._0,c):c});f(function(a,b){return p(fa,tc(a),h.fromArray([]),b)});var wb=function(a){return p(sa,f(function(a,c){return e(y["::"],a,c)}),h.fromArray([]),a)};l(function(a,b,c){var d=f(function(b,
c){return"::"===c.ctor?e(y["::"],e(a,b,c._0),c):h.fromArray([])});return wb(p(sa,d,h.fromArray([b]),c))});var uc=f(function(a,b){return"[]"===b.ctor?a:p(fa,f(function(a,b){return e(y["::"],a,b)}),b,a)});f(function(a,b){a=e(ia,a,b);return p(fa,uc,h.fromArray([]),a)});f(function(a,b){var c=f(function(b,c){var d=c._0;c=c._1;return a(b)?{ctor:"_Tuple2",_0:e(y["::"],b,d),_1:c}:{ctor:"_Tuple2",_0:d,_1:e(y["::"],b,c)}});return p(fa,c,{ctor:"_Tuple2",_0:h.fromArray([]),_1:h.fromArray([])},b)});f(function(a,
b){if("[]"===b.ctor)return h.fromArray([]);var c=f(function(b,c){return e(y["::"],a,e(y["::"],b,c))}),c=p(fa,c,h.fromArray([]),b._1);return e(y["::"],b._0,c)});var vc=l(function(a,b,c){for(;;){if(1>q.cmp(a,0))return c;var d=b;if("[]"===d.ctor)return c;--a;b=d._1;c=e(y["::"],d._0,c)}}),wc=f(function(a,b){return wb(p(vc,a,b,h.fromArray([])))}),xb=l(function(a,b,c){if(1>q.cmp(b,0))return h.fromArray([]);a:do{b:do{if("[]"===c.ctor)return c;if("::"===c._1.ctor)switch(b){case 1:break b;case 2:return h.fromArray([c._0,
c._1._0]);case 3:if("::"===c._1._1.ctor)return h.fromArray([c._0,c._1._0,c._1._1._0]);break a;default:if("::"===c._1._1.ctor&&"::"===c._1._1._1.ctor){var d=c._1._1._0,f=c._1._0,T=c._0,l=c._1._1._1._0;c=c._1._1._1._1;return 0<q.cmp(a,1E3)?e(y["::"],T,e(y["::"],f,e(y["::"],d,e(y["::"],l,e(wc,b-4,c))))):e(y["::"],T,e(y["::"],f,e(y["::"],d,e(y["::"],l,p(xb,a+1,b-4,c)))))}break a}else if(1===b)break b;else break a}while(0);return h.fromArray([c._0])}while(0);return c});f(function(a,b){return p(xb,0,a,
b)});var xc=l(function(a,b,c){for(;;){if(1>q.cmp(b,0))return a;a=e(y["::"],c,a);--b}});f(function(a,b){return p(xc,h.fromArray([]),a,b)});f(function(a,b){return"Ok"===b.ctor?b._0:a});var B=function(a){return{ctor:"Err",_0:a}};f(function(a,b){return"Ok"===a.ctor?b(a._0):B(a._0)});var Z=function(a){return{ctor:"Ok",_0:a}};f(function(a,b){return"Ok"===b.ctor?Z(a(b._0)):B(b._0)});l(function(a,b,c){return"Ok"===b.ctor?"Ok"===c.ctor?Z(e(a,b._0,c._0)):B(c._0):B(b._0)});w(function(a,b,c,d){return"Ok"===b.ctor?
"Ok"===c.ctor?"Ok"===d.ctor?Z(p(a,b._0,c._0,d._0)):B(d._0):B(c._0):B(b._0)});D(function(a,b,c,d,e){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===e.ctor?Z(aa(a,b._0,c._0,d._0,e._0)):B(e._0):B(d._0):B(c._0):B(b._0)});S(function(a,b,c,d,e,f){return"Ok"===b.ctor?"Ok"===c.ctor?"Ok"===d.ctor?"Ok"===e.ctor?"Ok"===f.ctor?Z(v(a,b._0,c._0,d._0,e._0,f._0)):B(f._0):B(e._0):B(d._0):B(c._0):B(b._0)});f(function(a,b){return"Ok"===b.ctor?Z(b._0):B(a(b._0))});f(function(a,b){return"Just"===b.ctor?Z(b._0):
B(a)});var U=function(){function a(a){return function(c){var d="Cannot initialize module `"+a+"` because it has no `main` value!\nWhat should I show on screen?";c.innerHTML=b(d);throw Error(d);}}function b(a){return'<div style="padding-left:1em;"><h2 style="font-weight:normal;"><b>Oops!</b> Something went wrong when starting your Elm program.</h2><pre style="padding-left:1em;">'+a+"</pre></div>"}function c(a,c){return function(k,e,f){try{var u=g(a,c);f||(u.renderer=d);return n(a,u,k,e)}catch(yb){throw k.innerHTML=
b(yb.message),yb;}}}function d(){return{update:function(){}}}function g(a,b){var c=b.main;if("undefined"===typeof c.init){var d=ta(h.Nil),k=q.Tuple2(q.Tuple0,d);return ua({init:function(){return k},view:function(){return c},update:f(function(){return k}),subscriptions:function(){return d}})}a=(b=b.flags)?m(a,c.init,b):T(a,c.init);return ua({init:a,view:c.view,update:c.update,subscriptions:c.subscriptions})}function T(a,b){return function(c){if("undefined"!==typeof c)throw Error("You are giving module `"+
a+"` an argument in JavaScript.\nThis module does not take arguments though! You probably need to change the\ninitialization code to something like `Elm."+a+".fullscreen()`");return b()}}function m(a,b,c){return function(d){d=e(P.run,c,d);if("Err"===d.ctor)throw Error("You are trying to initialize module `"+a+"` with an unexpected argument.\nWhen trying to convert it to a usable Elm value, I run into this problem:\n\n"+d._0);return b(d._0)}}function n(a,b,c,d){function f(a){x.rawSend(K,a)}var u=b.init,
g=b.update,ba=b.subscriptions,ca=b.view,Ga=b.renderer,t={},H;a=x.nativeBinding(function(a){var b=u(d),k=b._0;H=Ga(c,f,ca(k));var b=b._1,e=ba(k);ja(t,b,e);a(x.succeed(k))});var K=k(a,function(a,b){return x.nativeBinding(function(c){var d=e(g,a,b);b=d._0;H.update(ca(b));var d=d._1,k=ba(b);ja(t,d,k);c(x.succeed(b))})});return(a=r(t,f))?{ports:a}:{}}function r(a,b){var c,d;for(d in C){var k=C[d];k.isForeign&&(c=c||{},c[d]="cmd"===k.tag?t(d):R(d,b));a[d]=nc(k,b)}return c}function nc(a,b){var c={main:b,
self:void 0},d=a.tag,e=a.onEffects,f=a.onSelfMsg;a=k(a.init,function(a,b){if("self"===a.ctor)return p(f,c,a._0,b);a=a._0;switch(d){case "cmd":return p(e,c,a.cmds,b);case "sub":return p(e,c,a.subs,b);case "fx":return aa(e,c,a.cmds,a.subs,b)}});return c.self=a}function k(a,b){function c(a){var k=x.receive(function(c){return b(c,a)});return e(d,k,c)}var d=x.andThen;a=e(d,a,c);return x.rawSpawn(a)}function H(a){return function(b){return{type:"leaf",home:a,value:b}}}function ta(a){return{type:"node",branches:a}}
function ja(a,b,c){var d={};ka(!0,b,d,null);ka(!1,c,d,null);for(var k in a)x.rawSend(a[k],{ctor:"fx",_0:k in d?d[k]:{cmds:h.Nil,subs:h.Nil}})}function ka(a,b,c,d){switch(b.type){case "leaf":var k=b.home;d=w(a,k,d,b.value);b=(b=c[k])||{cmds:h.Nil,subs:h.Nil};a?b.cmds=h.Cons(d,b.cmds):b.subs=h.Cons(d,b.subs);c[k]=b;break;case "node":for(k=b.branches;"[]"!==k.ctor;)ka(a,k._0,c,d),k=k._1;break;case "map":ka(a,b.tree,c,{tagger:b.tagger,rest:d})}}function w(a,b,c,d){return e(a?C[b].cmdMap:C[b].subMap,function(a){for(var b=
c;b;)a=b.tagger(a),b=b.rest;return a},d)}function u(a){if(a in C)throw Error("There can only be one port named `"+a+"`, but your program has multiple.");}function t(a){var b=[],c=C[a].converter,d=x.succeed(null);C[a].init=d;C[a].onEffects=l(function(a,k,e){for(;"[]"!==k.ctor;){a=c(k._0);for(e=0;e<b.length;e++)b[e](a);k=k._1}return d});return{subscribe:function(a){b.push(a)},unsubscribe:function(a){a=b.indexOf(a);0<=a&&b.splice(a,1)}}}function R(a,b){function c(a,b,c){f=b;return Ga}function d(c){c=
e(zb,u,c);if("Err"===c.ctor)throw Error("Trying to send an unexpected type of value through port `"+a+"`:\n"+c._0);c=c._0;for(var d=f;"[]"!==d.ctor;)b(d._0(c)),d=d._1}var k=[],f=h.Nil,u=C[a].converter,ba=function(a,b,e){a=c(a,b,e);for(b=0;b<k.length;b++)d(k[b]);k=null;ca=d;ba=c;return a},ca=function(a){k.push(a)},Ga=x.succeed(null);C[a].init=Ga;C[a].onEffects=l(function(a,b,c){return ba(a,b,c)});return{send:function(a){ca(a)}}}var C={},K=f(function(a,b){return b}),F=f(function(a,b){return function(c){return a(b(c))}});
return{sendToApp:f(function(a,b){return x.nativeBinding(function(c){a.main(b);c(x.succeed(q.Tuple0))})}),sendToSelf:f(function(a,b){return e(x.send,a.self,{ctor:"self",_0:b})}),mainToProgram:g,effectManagers:C,outgoingPort:function(a,b){u(a);C[a]={tag:"cmd",cmdMap:K,converter:b,isForeign:!0};return H(a)},incomingPort:function(a,b){u(a);C[a]={tag:"sub",subMap:F,converter:b,isForeign:!0};return H(a)},addPublicModule:function(b,d,k){var e=k?c(d,k):a(d);b.worker=function(a){return e(void 0,a,!1)};b.embed=
function(a,b){return e(a,b,!0)};b.fullscreen=function(a){return e(document.body,a,!0)}},leaf:H,batch:ta,map:f(function(a,b){return{type:"map",tagger:a,tree:b}})}}(),x=function(){function a(a){return{ctor:"_Task_succeed",value:a}}function b(a){return{ctor:"_Task_nativeBinding",callback:a,cancel:null}}function c(a){a={ctor:"_Process",id:q.guid(),root:a,stack:null,mailbox:[]};h(a);return a}function d(a,b){a.mailbox.push(b);h(a)}function e(a,b){for(;1E4>a;){var c=b.root.ctor;if("_Task_succeed"===c){for(;b.stack&&
"_Task_onError"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_fail"===c){for(;b.stack&&"_Task_andThen"===b.stack.ctor;)b.stack=b.stack.rest;if(null===b.stack)break;b.root=b.stack.callback(b.root.value);b.stack=b.stack.rest;++a}else if("_Task_andThen"===c)b.stack={ctor:"_Task_andThen",callback:b.root.callback,rest:b.stack},b.root=b.root.task,++a;else if("_Task_onError"===c)b.stack={ctor:"_Task_onError",callback:b.root.callback,
rest:b.stack},b.root=b.root.task,++a;else{if("_Task_nativeBinding"===c){b.root.cancel=b.root.callback(function(a){b.root=a;h(b)});break}if("_Task_receive"===c){c=b.mailbox;if(0===c.length)break;b.root=b.root.callback(c.shift());++a}else throw Error(c);}}if(1E4>a)return a+1;h(b);return a}function h(a){n.push(a);m||(setTimeout(l,0),m=!0)}function l(){for(var a=0,b;1E4>a&&(b=n.shift());)b.root&&(a=e(a,b));b?setTimeout(l,0):m=!1}var m=!1,n=[];return{succeed:a,fail:function(a){return{ctor:"_Task_fail",
value:a}},nativeBinding:b,andThen:f(function(a,b){return{ctor:"_Task_andThen",task:a,callback:b}}),onError:f(function(a,b){return{ctor:"_Task_onError",task:a,callback:b}}),receive:function(a){return{ctor:"_Task_receive",callback:a}},spawn:function(d){return b(function(b){var e=c(d);b(a(e))})},kill:function(c){return b(function(b){var d=c.root;"_Task_nativeBinding"===d.ctor&&d.cancel&&d.cancel();c.root=null;b(a(q.Tuple0))})},sleep:function(c){return b(function(b){var d=setTimeout(function(){b(a(q.Tuple0))},
c);return function(){clearTimeout(d)}})},send:f(function(c,e){return b(function(b){d(c,e);b(a(q.Tuple0))})}),rawSpawn:c,rawSend:d}}(),Ab=U.sendToSelf,Za=U.sendToApp,Bb=U.batch,Cb=Bb(h.fromArray([])),Db=Db||{};Db["!"]=f(function(a,b){return{ctor:"_Tuple2",_0:a,_1:Bb(b)}});var yc=U.batch;yc(h.fromArray([]));var E=function(){function a(b,c,d){d=K(d);if(0===d.height)d.table[b]=c;else{var e=Va(b,d);0<e&&(b-=d.lengths[e-1]);d.table[e]=a(b,c,d.table[e])}return d}function b(a,c,d,e){if(0===c){for(var k=Array((e-
d)%33),f=0;f<k.length;f++)k[f]=a(d+f);return{ctor:"_Array",height:0,table:k}}for(var ca=Math.pow(32,c),k=Array(Math.ceil((e-d)/ca)),ba=Array(k.length),f=0;f<k.length;f++)k[f]=b(a,c-1,d+f*ca,Math.min(d+(f+1)*ca,e)),ba[f]=F(k[f])+(0<f?ba[f-1]:0);return{ctor:"_Array",height:c,table:k,lengths:ba}}function c(a,b){var d=a.height;b.length===d&&b.push({ctor:"_Array",height:d+1,table:[],lengths:[]});b[d].table.push(a);a=F(a);0<b[d].lengths.length&&(a+=b[d].lengths[b[d].lengths.length-1]);b[d].lengths.push(a);
32===b[d].table.length&&(c(b[d],b),b[d]={ctor:"_Array",height:d+1,table:[],lengths:[]})}function d(a,b){if(0===b.height)return 32>b.table.length?(b={ctor:"_Array",height:0,table:b.table.slice()},b.table.push(a),b):null;var c=d(a,b.table[b.table.length-1]);return null!==c?(b=K(b),b.table[b.table.length-1]=c,b.lengths[b.lengths.length-1]++,b):32>b.table.length?(a=Wa(a,b.height-1),b=K(b),b.table.push(a),b.lengths.push(b.lengths[b.lengths.length-1]+F(a)),b):null}function g(a,b){for(var c=b.table.length-
1;0<=c;c--)a=0===b.height?h.Cons(b.table[c],a):g(a,b.table[c]);return a}function T(a,b){var c={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(c.lengths=b.lengths);for(var d=0;d<b.table.length;d++)c.table[d]=0===b.height?a(b.table[d]):T(a,b.table[d]);return c}function m(a,b,c){var d={ctor:"_Array",height:b.height,table:Array(b.table.length)};0<b.height&&(d.lengths=b.lengths);for(var k=0;k<b.table.length;k++)d.table[k]=0===b.height?e(a,c+k,b.table[k]):m(a,b.table[k],0==k?c:
c+b.lengths[k-1]);return d}function n(a,b,c){if(0===c.height)for(var d=0;d<c.table.length;d++)b=e(a,c.table[d],b);else for(d=0;d<c.table.length;d++)b=n(a,b,c.table[d]);return b}function p(a,b,c){if(0===c.height)for(var d=c.table.length;d--;)b=e(a,c.table[d],b);else for(d=c.table.length;d--;)b=p(a,b,c.table[d]);return b}function q(a,b){if(a===F(b))return b;if(0===b.height){var c={ctor:"_Array",height:0};c.table=b.table.slice(0,a);return c}var d=Va(a,b);a=q(a-(0<d?b.lengths[d-1]:0),b.table[d]);if(0===
d)return a;c={ctor:"_Array",height:b.height,table:b.table.slice(0,d),lengths:b.lengths.slice(0,d)};0<a.table.length&&(c.table[d]=a,c.lengths[d]=F(a)+(0<d?c.lengths[d-1]:0));return c}function k(a,b){if(0===a)return b;if(0===b.height){var c={ctor:"_Array",height:0};c.table=b.table.slice(a,b.table.length+1);return c}c=Va(a,b);a=k(a-(0<c?b.lengths[c-1]:0),b.table[c]);if(c===b.table.length-1)return a;c={ctor:"_Array",height:b.height,table:b.table.slice(c,b.table.length+1),lengths:Array(b.table.length-
c)};c.table[0]=a;for(a=b=0;a<c.table.length;a++)b+=F(c.table[a]),c.lengths[a]=b;return c}function H(a,b){if(0===a.height&&0===b.height)return[a,b];if(1!==a.height||1!==b.height)if(a.height===b.height){a=K(a);b=K(b);var c=H(a.table[a.table.length-1],b.table[0]);ta(a,c[1]);ja(b,c[0])}else if(a.height>b.height)a=K(a),c=H(a.table[a.table.length-1],b),ta(a,c[0]),b=Xa(c[1],c[1].height+1);else{b=K(b);c=H(a,b.table[0]);a=0===c[0].table.length?0:1;var d=0===a?1:0;ja(b,c[a]);a=Xa(c[d],c[d].height+1)}if(0===
a.table.length||0===b.table.length)return[a,b];c=ka(a,b);return 2>=c?[a,b]:C(a,b,c)}function ta(a,b){var c=a.table.length-1;a.table[c]=b;a.lengths[c]=F(b);a.lengths[c]+=0<c?a.lengths[c-1]:0}function ja(a,b){if(0<b.table.length){a.table[0]=b;a.lengths[0]=F(b);b=F(a.table[0]);for(var c=1;c<a.lengths.length;c++)b+=F(a.table[c]),a.lengths[c]=b}else{a.table.shift();for(c=1;c<a.lengths.length;c++)a.lengths[c]-=a.lengths[0];a.lengths.shift()}}function ka(a,b){for(var c=0,d=0;d<a.table.length;d++)c+=a.table[d].table.length;
for(d=0;d<b.table.length;d++)c+=b.table[d].table.length;return a.table.length+b.table.length-(Math.floor((c-1)/32)+1)}function r(a,b,c){return c<a.length?a[c]:b[c-a.length]}function u(a,b,c,d){c<a.length?a[c]=d:b[c-a.length]=d}function t(a,b,c,d){u(a.table,b.table,c,d);var e=0===c||c===a.lengths.length?0:r(a.lengths,a.lengths,c-1);u(a.lengths,b.lengths,c,e+F(d))}function R(a,b){0>b&&(b=0);var c={ctor:"_Array",height:a,table:Array(b)};0<a&&(c.lengths=Array(b));return c}function C(a,b,c){for(var d=
R(a.height,Math.min(32,a.table.length+b.table.length-c)),e=R(a.height,d.table.length-(a.table.length+b.table.length-c)),k=0;0===r(a.table,b.table,k).table.length%32;)u(d.table,e.table,k,r(a.table,b.table,k)),u(d.lengths,e.lengths,k,r(a.lengths,b.lengths,k)),k++;for(var f=k,g=new R(a.height-1,0),K=0;k-f-(0<g.table.length?1:0)<c;){var H=r(a.table,b.table,k),C=Math.min(32-g.table.length,H.table.length);g.table=g.table.concat(H.table.slice(K,C));if(0<g.height)for(var h=g.lengths.length,l=h;l<h+C-K;l++)g.lengths[l]=
F(g.table[l]),g.lengths[l]+=0<l?g.lengths[l-1]:0;K+=C;H.table.length<=C&&(k++,K=0);32===g.table.length&&(t(d,e,f,g),g=R(a.height-1,0),f++)}0<g.table.length&&(t(d,e,f,g),f++);for(;k<a.table.length+b.table.length;)t(d,e,f,r(a.table,b.table,k)),k++,f++;return[d,e]}function K(a){var b={ctor:"_Array",height:a.height,table:a.table.slice()};0<a.height&&(b.lengths=a.lengths.slice());return b}function F(a){return 0===a.height?a.table.length:a.lengths[a.lengths.length-1]}function Va(a,b){for(var c=a>>5*b.height;b.lengths[c]<=
a;)c++;return c}function Wa(a,b){return 0===b?{ctor:"_Array",height:0,table:[a]}:{ctor:"_Array",height:b,table:[Wa(a,b-1)],lengths:[1]}}function Xa(a,b){return b===a.height?a:{ctor:"_Array",height:b,table:[Xa(a,b-1)],lengths:[F(a)]}}function Ya(a,b){return{ctor:"_Array",height:a.height+1,table:[a,b],lengths:[F(a),F(a)+F(b)]}}function w(a,b,c){for(var d=0;d<c.table.length;d++)0===c.height?a[b+d]=c.table[d]:w(a,b+(0===d?0:c.lengths[d-1]),c.table[d])}function v(a,b,c,d){if(0===b)return{ctor:"_Array",
height:0,table:a.slice(c,d)};for(var e=Math.pow(32,b),k=Array(Math.ceil((d-c)/e)),f=Array(k.length),g=0;g<k.length;g++)k[g]=v(a,b-1,c+g*e,Math.min(c+(g+1)*e,d)),f[g]=F(k[g])+(0<g?f[g-1]:0);return{ctor:"_Array",height:b,table:k,lengths:f}}var x={ctor:"_Array",height:0,table:[]};return{empty:x,fromList:function(a){if("[]"===a.ctor)return x;for(var b=Array(32),d=[],e=0;"[]"!==a.ctor;)b[e]=a._0,a=a._1,e++,32===e&&(b={ctor:"_Array",height:0,table:b},c(b,d),b=Array(32),e=0);0<e&&(b={ctor:"_Array",height:0,
table:b.splice(0,e)},c(b,d));for(a=0;a<d.length-1;a++)0<d[a].table.length&&c(d[a],d);d=d[d.length-1];return 0<d.height&&1===d.table.length?d.table[0]:d},toList:function(a){return g(h.Nil,a)},initialize:f(function(a,c){return 0>=a?x:b(c,Math.floor(Math.log(a)/Math.log(32)),0,a)}),append:f(function(a,b){if(0===a.table.length)return b;if(0===b.table.length)return a;var c=H(a,b);if(32>=c[0].table.length+c[1].table.length){if(0===c[0].table.length)return c[1];if(0===c[1].table.length)return c[0];c[0].table=
c[0].table.concat(c[1].table);if(0<c[0].height){a=F(c[0]);for(b=0;b<c[1].lengths.length;b++)c[1].lengths[b]+=a;c[0].lengths=c[0].lengths.concat(c[1].lengths)}return c[0]}0<c[0].height&&(a=ka(a,b),2<a&&(c=C(c[0],c[1],a)));return Ya(c[0],c[1])}),push:f(function(a,b){var c=d(a,b);if(null!==c)return c;a=Wa(a,b.height);return Ya(b,a)}),slice:l(function(a,b,c){0>a&&(a+=F(c));0>b&&(b+=F(c));return k(a,q(b,c))}),get:f(function(a,b){if(0>a||a>=F(b))throw Error("Index "+a+" is out of range. Check the length of your array first or use getMaybe or getWithDefault.");
for(var c=b.height;0<c;c--){for(var d=a>>5*c;b.lengths[d]<=a;)d++;0<d&&(a-=b.lengths[d-1]);b=b.table[d]}return b.table[a]}),set:l(function(b,c,d){return 0>b||F(d)<=b?d:a(b,c,d)}),map:f(T),indexedMap:f(function(a,b){return m(a,b,0)}),foldl:l(n),foldr:l(p),length:F,toJSArray:function(a){var b=Array(F(a));w(b,0,a);return b},fromJSArray:function(a){return 0===a.length?x:v(a,Math.floor(Math.log(a.length)/Math.log(32)),0,a.length)}}}(),va=E.append,V=E.length,W=E.slice,Ha=E.set,Eb=f(function(a,b){return 1>
q.cmp(0,a)&&0>q.cmp(a,E.length(b))?L(e(E.get,a,b)):J}),zc=E.push,wa=E.empty,Ac=f(function(a,b){var c=f(function(b,c){return a(b)?e(E.push,b,c):c});return p(E.foldl,c,E.empty,b)}),Bc=E.foldl,Ia=E.indexedMap,Cc=E.map,ha=E.toList,$a=E.fromList,Dc=E.initialize,Ja=f(function(a,b){return e(Dc,a,Ta(b))}),Ec=f(function(a,b){var c=V(b),d=0<q.cmp(a,0),e=0>q.cmp(a,c);return!0===d?!0===e?{ctor:"_Tuple2",_0:p(W,0,a,b),_1:p(W,a,c,b)}:{ctor:"_Tuple2",_0:b,_1:wa}:!0===e?{ctor:"_Tuple2",_0:wa,_1:b}:{ctor:"_Tuple2",
_0:wa,_1:wa}}),Fc=f(function(a,b){b=e(Ec,a,b);a=b._0;b=b._1;var c=V(b);return q.eq(c,0)?a:e(va,a,p(W,1,c,b))});l(function(a,b,c){var d=f(function(a,b){return e(Ia,f(function(a,c){return b(a)}),e(Ja,a,{ctor:"_Tuple0"}))}),g=V(c);return 0<q.cmp(g,a)?p(W,g-a,g,c):0>q.cmp(g,a)?e(va,e(d,a-g,b),c):c});l(function(a,b,c){var d=f(function(a,b){return e(Ia,f(function(a,c){return b(a)}),e(Ja,a,{ctor:"_Tuple0"}))}),g=V(c);return 0<q.cmp(g,a)?p(W,0,a,c):0>q.cmp(g,a)?e(va,c,e(d,a-g,function(a){return b(a+g)})):
c});l(function(a,b,c){var d=V(c);return 0<q.cmp(d,a)?p(W,d-a,d,c):0>q.cmp(d,a)?e(va,e(Ja,a-d,b),c):c});l(function(a,b,c){var d=V(c);return 0<q.cmp(d,a)?p(W,0,a,c):0>q.cmp(d,a)?e(va,c,e(Ja,a-d,b)):c});f(function(a,b){return e(Ac,function(b){return qa(a(b))},b)});f(function(a,b){var c=l(function(a,b,c){a=a(b);return"Just"===a.ctor?e(zc,a._0,c):c});return p(Bc,c(a),wa,b)});var Gc=f(function(a,b){var c=e(Eb,a,b);return"Just"===c.ctor?c._0:q.crashCase("Array.Extra",{start:{line:73,column:5},end:{line:78,
column:125}},c)(e(r["++"],"Index ",e(r["++"],ea(a),e(r["++"]," of Array with length ",e(r["++"],ea(V(b))," is not reachable.")))))}),Ka=f(function(a,b){var c=e(oc,V(a),V(b));a=p(W,0,c,a);return e(Ia,f(function(a,c){return c(e(Gc,a,b))}),a)}),Fb=f(function(a,b){return Ka(e(Cc,a,b))});Fb(f(function(a,b){return{ctor:"_Tuple2",_0:a,_1:b}}));var Gb=l(function(a,b,c){return Ka(p(Fb,a,b,c))});Gb(l(function(a,b,c){return{ctor:"_Tuple3",_0:a,_1:b,_2:c}}));var Hb=w(function(a,b,c,d){return Ka(aa(Gb,a,b,c,d))});
Hb(w(function(a,b,c,d){return{ctor:"_Tuple4",_0:a,_1:b,_2:c,_3:d}}));D(function(a,b,c,d,e){return Ka(v(Hb,a,b,c,d,e))})(D(function(a,b,c,d,e){return{ctor:"_Tuple5",_0:a,_1:b,_2:c,_3:d,_4:e}}));f(function(a,b){return-1<q.cmp(a,0)?p(W,0,a,b):p(W,0,V(b)+a,b)});f(function(a,b){return p(W,a,V(b),b)});l(function(a,b,c){var d=e(Eb,a,c);return"Nothing"===d.ctor?c:p(Ha,a,b(d._0),c)});var Ib=x.onError,z=x.andThen,Hc=f(function(a,b){return x.spawn(e(z,b._0,Za(a)))}),Jb=x.fail;f(function(a,b){return e(Ib,b,function(b){return Jb(a(b))})});
var A=x.succeed,ab=f(function(a,b){return e(z,b,function(b){return A(a(b))})}),Ic=l(function(a,b,c){return e(z,b,function(b){return e(z,c,function(c){return A(e(a,b,c))})})});w(function(a,b,c,d){return e(z,b,function(b){return e(z,c,function(c){return e(z,d,function(d){return A(p(a,b,c,d))})})})});D(function(a,b,c,d,f){return e(z,b,function(b){return e(z,c,function(c){return e(z,d,function(d){return e(z,f,function(e){return A(aa(a,b,c,d,e))})})})})});S(function(a,b,c,d,f,h){return e(z,b,function(b){return e(z,
c,function(c){return e(z,d,function(d){return e(z,f,function(f){return e(z,h,function(e){return A(v(a,b,c,d,f,e))})})})})})});f(function(a,b){return e(z,a,function(a){return e(z,b,function(b){return A(a(b))})})});var La=function(a){return"[]"===a.ctor?A(h.fromArray([])):p(Ic,f(function(a,c){return e(y["::"],a,c)}),a._0,La(a._1))},Jc=l(function(a,b,c){return e(ab,function(a){return{ctor:"_Tuple0"}},La(e(ia,Hc(a),b)))});f(function(a,b){return"Just"===b.ctor?A(b._0):Jb(a)});var Kc=A({ctor:"_Tuple0"}),
Lc=l(function(a,b,c){return A({ctor:"_Tuple0"})}),Mc=U.leaf("Task");l(function(a,b,c){return Mc({ctor:"T",_0:e(Ib,e(ab,b,c),function(b){return A(a(b))})})});var Nc=f(function(a,b){return{ctor:"T",_0:e(ab,a,b._0)}});U.effectManagers.Task={pkg:"elm-lang/core",init:Kc,onEffects:Jc,onSelfMsg:Lc,tag:"cmd",cmdMap:Nc};var Oc=function(){function a(a,c){for(var b="";0<a;)a&1&&(b+=c),a>>=1,c+=c;return b}return{isEmpty:function(a){return 0===a.length},cons:f(function(a,c){return a+c}),uncons:function(a){var b=
a[0];return b?L(q.Tuple2(q.chr(b),a.slice(1))):J},append:f(function(a,c){return a+c}),concat:function(a){return h.toArray(a).join("")},length:function(a){return a.length},map:f(function(a,c){c=c.split("");for(var b=c.length;b--;)c[b]=a(q.chr(c[b]));return c.join("")}),filter:f(function(a,c){return c.split("").map(q.chr).filter(a).join("")}),reverse:function(a){return a.split("").reverse().join("")},foldl:l(function(a,c,d){for(var b=d.length,f=0;f<b;++f)c=e(a,q.chr(d[f]),c);return c}),foldr:l(function(a,
c,d){for(var b=d.length;b--;)c=e(a,q.chr(d[b]),c);return c}),split:f(function(a,c){return h.fromArray(c.split(a))}),join:f(function(a,c){return h.toArray(c).join(a)}),repeat:f(a),slice:l(function(a,c,d){return d.slice(a,c)}),left:f(function(a,c){return 1>a?"":c.slice(0,a)}),right:f(function(a,c){return 1>a?"":c.slice(-a)}),dropLeft:f(function(a,c){return 1>a?c:c.slice(a)}),dropRight:f(function(a,c){return 1>a?c:c.slice(0,-a)}),pad:l(function(b,c,d){b=(b-d.length)/2;return a(Math.ceil(b),c)+d+a(b|
0,c)}),padLeft:l(function(b,c,d){return a(b-d.length,c)+d}),padRight:l(function(b,c,d){return d+a(b-d.length,c)}),trim:function(a){return a.trim()},trimLeft:function(a){return a.replace(/^\s+/,"")},trimRight:function(a){return a.replace(/\s+$/,"")},words:function(a){return h.fromArray(a.trim().split(/\s+/g))},lines:function(a){return h.fromArray(a.split(/\r\n|\r|\n/g))},toUpper:function(a){return a.toUpperCase()},toLower:function(a){return a.toLowerCase()},any:f(function(a,c){for(var b=c.length;b--;)if(a(q.chr(c[b])))return!0;
return!1}),all:f(function(a,c){for(var b=c.length;b--;)if(!a(q.chr(c[b])))return!1;return!0}),contains:f(function(a,c){return-1<c.indexOf(a)}),startsWith:f(function(a,c){return 0===c.indexOf(a)}),endsWith:f(function(a,c){return c.length>=a.length&&c.lastIndexOf(a)===c.length-a.length}),indexes:f(function(a,c){var b=a.length;if(1>b)return h.Nil;for(var e=0,f=[];-1<(e=c.indexOf(a,e));)f.push(e),e+=b;return h.fromArray(f)}),toInt:function(a){var b=a.length;if(0===b)return B("could not convert string '"+
a+"' to an Int");var d=0;if("-"===a[0]){if(1===b)return B("could not convert string '"+a+"' to an Int");d=1}for(;d<b;++d){var e=a[d];if("0">e||"9"<e)return B("could not convert string '"+a+"' to an Int")}return Z(parseInt(a,10))},toFloat:function(a){var b=a.length;if(0===b)return B("could not convert string '"+a+"' to a Float");var d=0;if("-"===a[0]){if(1===b)return B("could not convert string '"+a+"' to a Float");d=1}for(var e=0;d<b;++d){var f=a[d];if(!("0"<=f&&"9">=f)){if("."===f&&(e+=1,1>=e))continue;
return B("could not convert string '"+a+"' to a Float")}}return Z(parseFloat(a))},toList:function(a){return h.fromArray(a.split("").map(q.chr))},fromList:function(a){return h.toArray(a).join("")}}}(),bb=function(){return{fromCode:function(a){return q.chr(String.fromCharCode(a))},toCode:function(a){return a.charCodeAt(0)},toUpper:function(a){return q.chr(a.toUpperCase())},toLower:function(a){return q.chr(a.toLowerCase())},toLocaleUpper:function(a){return q.chr(a.toLocaleUpperCase())},toLocaleLower:function(a){return q.chr(a.toLocaleLowerCase())}}}().toCode,
Ma=l(function(a,b,c){c=bb(c);return-1<q.cmp(c,bb(a))&&1>q.cmp(c,bb(b))});e(Ma,q.chr("A"),q.chr("Z"));e(Ma,q.chr("a"),q.chr("z"));e(Ma,q.chr("0"),q.chr("9"));e(Ma,q.chr("0"),q.chr("7"));var Pc=Oc.concat,Kb=l(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===d.ctor)return b;c=a;b=p(a,d._1,d._2,p(Kb,a,b,d._4));d=d._3;a=c;c=d}}),Ea=function(a){return p(Kb,l(function(a,c,d){return e(y["::"],{ctor:"_Tuple2",_0:a,_1:c},d)}),h.fromArray([]),a)},ma=l(function(a,b,c){for(;;){var d=c;if("RBEmpty_elm_builtin"===
d.ctor)return b;c=a;b=p(a,d._1,d._2,p(ma,a,b,d._3));d=d._4;a=c;c=d}}),Lb=S(function(a,b,c,d,e,h){var g=l(function(d,e,f){for(;;){var k=f;f=k._1;var g=k._0,h=g;if("[]"===h.ctor)return{ctor:"_Tuple2",_0:g,_1:p(c,d,e,f)};var k=h._1,l=h._0._1,h=h._0._0;if(0>q.cmp(h,d))f={ctor:"_Tuple2",_0:k,_1:p(a,h,l,f)};else return 0<q.cmp(h,d)?{ctor:"_Tuple2",_0:g,_1:p(c,d,e,f)}:{ctor:"_Tuple2",_0:k,_1:aa(b,h,l,e,f)}}});e=p(ma,g,{ctor:"_Tuple2",_0:Ea(d),_1:h},e);d=e._0;e=e._1;return p(sa,f(function(b,c){return p(a,
b._0,b._1,c)}),e,d)}),Mb=w(function(a,b,c,d){return ra.crash(Pc(h.fromArray(["Internal red-black tree invariant violated, expected ",a," and got ",ea(b),"/",c,"/",d,"\nPlease report this bug to <https://github.com/elm-lang/core/issues>"])))}),Nb=function(a){a:do{if("RBNode_elm_builtin"===a.ctor){if("BBlack"===a._0.ctor)return!0}else if("LBBlack"===a._0.ctor)return!0;break a}while(0);return!1},Qc=f(function(a,b){for(;;){if("RBEmpty_elm_builtin"===b.ctor)return a;a=e(Qc,a+1,b._4);b=b._3}}),Na=f(function(a,
b){a:for(;;){if("RBEmpty_elm_builtin"===b.ctor)return J;switch(e(vb,a,b._1).ctor){case "LT":b=b._3;continue a;case "EQ":return L(b._2);default:b=b._4}}}),Rc=f(function(a,b){return"Just"===e(Na,a,b).ctor?!0:!1}),Sc=l(function(a,b,c){for(;;){if("RBEmpty_elm_builtin"===c.ctor)return{ctor:"_Tuple2",_0:a,_1:b};b=c._2;var d=c._4;a=c._1;c=d}}),Tc={ctor:"NBlack"},Ob={ctor:"BBlack"},M={ctor:"Black"},Oa={ctor:"Red"},Uc=function(a){switch(a.ctor){case "Black":return Ob;case "Red":return M;case "NBlack":return Oa;
default:return ra.crash("Can't make a double black node more black!")}},Pb=function(a){switch(a.ctor){case "BBlack":return M;case "Black":return Oa;case "Red":return Tc;default:return ra.crash("Can't make a negative black node less black!")}},Vc={ctor:"LBBlack"},xa={ctor:"LBlack"},na=function(a){return{ctor:"RBEmpty_elm_builtin",_0:a}},N=na(xa),G=D(function(a,b,c,d,e){return{ctor:"RBNode_elm_builtin",_0:a,_1:b,_2:c,_3:d,_4:e}}),Wc=function(a){return"RBNode_elm_builtin"===a.ctor&&"Red"===a._0.ctor?
v(G,M,a._1,a._2,a._3,a._4):a},Qb=function(a){return"RBNode_elm_builtin"===a.ctor?v(G,Pb(a._0),a._1,a._2,a._3,a._4):na(xa)},Pa=function(a){return function(b){return function(c){return function(d){return function(e){return function(f){return function(g){return function(h){return function(l){return function(m){return function(k){return v(G,Pb(a),d,e,v(G,M,b,c,h,l),v(G,M,f,g,m,k))}}}}}}}}}}},Xc=function(a){return"RBEmpty_elm_builtin"===a.ctor?na(xa):v(G,M,a._1,a._2,a._3,a._4)},Rb=function(a){return"RBEmpty_elm_builtin"===
a.ctor?ra.crash("can't make a Leaf red"):v(G,Oa,a._1,a._2,a._3,a._4)},Yc=function(a){a:do{b:do{c:do{d:do{e:do{f:do{g:do if("RBNode_elm_builtin"===a.ctor)if("RBNode_elm_builtin"===a._3.ctor)if("RBNode_elm_builtin"===a._4.ctor)switch(a._3._0.ctor){case "Red":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;
else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;
else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===a._3._4._0.ctor)break f;else break a}case "NBlack":switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;case "NBlack":if("BBlack"===a._0.ctor)if("RBNode_elm_builtin"===
a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else if("RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;else break a;default:if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a}default:switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===
a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}}else switch(a._3._0.ctor){case "Red":if("RBNode_elm_builtin"===a._3._3.ctor&&"Red"===a._3._3._0.ctor)break g;else if("RBNode_elm_builtin"===a._3._4.ctor&&"Red"===
a._3._4._0.ctor)break f;else break a;case "NBlack":if("BBlack"===a._0.ctor&&"RBNode_elm_builtin"===a._3._3.ctor&&"Black"===a._3._3._0.ctor&&"RBNode_elm_builtin"===a._3._4.ctor&&"Black"===a._3._4._0.ctor)break b;else break a;default:break a}else if("RBNode_elm_builtin"===a._4.ctor)switch(a._4._0.ctor){case "Red":if("RBNode_elm_builtin"===a._4._3.ctor&&"Red"===a._4._3._0.ctor)break e;else if("RBNode_elm_builtin"===a._4._4.ctor&&"Red"===a._4._4._0.ctor)break d;else break a;case "NBlack":if("BBlack"===
a._0.ctor&&"RBNode_elm_builtin"===a._4._3.ctor&&"Black"===a._4._3._0.ctor&&"RBNode_elm_builtin"===a._4._4.ctor&&"Black"===a._4._4._0.ctor)break c;else break a;default:break a}else break a;else break a;while(0);return Pa(a._0)(a._3._3._1)(a._3._3._2)(a._3._1)(a._3._2)(a._1)(a._2)(a._3._3._3)(a._3._3._4)(a._3._4)(a._4)}while(0);return Pa(a._0)(a._3._1)(a._3._2)(a._3._4._1)(a._3._4._2)(a._1)(a._2)(a._3._3)(a._3._4._3)(a._3._4._4)(a._4)}while(0);return Pa(a._0)(a._1)(a._2)(a._4._3._1)(a._4._3._2)(a._4._1)(a._4._2)(a._3)(a._4._3._3)(a._4._3._4)(a._4._4)}while(0);
return Pa(a._0)(a._1)(a._2)(a._4._1)(a._4._2)(a._4._4._1)(a._4._4._2)(a._3)(a._4._3)(a._4._4._3)(a._4._4._4)}while(0);return v(G,M,a._4._3._1,a._4._3._2,v(G,M,a._1,a._2,a._3,a._4._3._3),v(ya,M,a._4._1,a._4._2,a._4._3._4,Rb(a._4._4)))}while(0);return v(G,M,a._3._4._1,a._3._4._2,v(ya,M,a._3._1,a._3._2,Rb(a._3._3),a._3._4._3),v(G,M,a._1,a._2,a._3._4._4,a._4))}while(0);return a},ya=D(function(a,b,c,d,e){a=v(G,a,b,c,d,e);"RBNode_elm_builtin"===a.ctor?(b=a._0,b=q.eq(b,M)||q.eq(b,Ob)):b=!0;return b?Yc(a):
a}),Qa=D(function(a,b,c,d,e){return Nb(d)||Nb(e)?v(ya,Uc(a),b,c,Qb(d),Qb(e)):v(G,a,b,c,d,e)}),Tb=D(function(a,b,c,d,e){return"RBEmpty_elm_builtin"===e.ctor?p(Sb,a,d,e):v(Qa,a,b,c,d,v(Tb,e._0,e._1,e._2,e._3,e._4))}),Sb=l(function(a,b,c){if("RBEmpty_elm_builtin"===b.ctor)if("RBEmpty_elm_builtin"===c.ctor)switch(a.ctor){case "Red":return na(xa);case "Black":return na(Vc);default:return ra.crash("cannot have bblack or nblack nodes at this point")}else{var d=c._0;b=b._0;return"Black"===a.ctor&&"LBlack"===
b.ctor&&"Red"===d.ctor?v(G,M,c._1,c._2,c._3,c._4):aa(Mb,"Black/LBlack/Red",a,ea(b),ea(d))}else{if("RBEmpty_elm_builtin"===c.ctor)return c=c._0,d=b._0,"Black"===a.ctor&&"Red"===d.ctor&&"LBlack"===c.ctor?v(G,M,b._1,b._2,b._3,b._4):aa(Mb,"Black/Red/LBlack",a,ea(d),ea(c));var d=b._2,e=b._4,f=b._1;b=v(Tb,b._0,f,d,b._3,e);d=p(Sc,f,d,e);return v(Qa,a,d._0,d._1,b,c)}}),Ub=f(function(a,b){if("RBEmpty_elm_builtin"===b.ctor)return na(xa);var c=b._1;return v(G,b._0,c,e(a,c,b._2),e(Ub,a,b._3),e(Ub,a,b._4))}),
Ra={ctor:"Same"},cb={ctor:"Remove"},db={ctor:"Insert"},eb=l(function(a,b,c){var d=function(c){if("RBEmpty_elm_builtin"===c.ctor){var f=b(J);return"Nothing"===f.ctor?{ctor:"_Tuple2",_0:Ra,_1:N}:{ctor:"_Tuple2",_0:db,_1:v(G,Oa,a,f._0,N,N)}}var g=c._2,h=c._4,l=c._3,f=c._1;c=c._0;switch(e(vb,a,f).ctor){case "EQ":return g=b(L(g)),"Nothing"===g.ctor?{ctor:"_Tuple2",_0:cb,_1:p(Sb,c,l,h)}:{ctor:"_Tuple2",_0:Ra,_1:v(G,c,f,g._0,l,h)};case "LT":var l=d(l),k=l._0,l=l._1;switch(k.ctor){case "Same":return{ctor:"_Tuple2",
_0:Ra,_1:v(G,c,f,g,l,h)};case "Insert":return{ctor:"_Tuple2",_0:db,_1:v(ya,c,f,g,l,h)};default:return{ctor:"_Tuple2",_0:cb,_1:v(Qa,c,f,g,l,h)}}default:switch(h=d(h),k=h._0,h=h._1,k.ctor){case "Same":return{ctor:"_Tuple2",_0:Ra,_1:v(G,c,f,g,l,h)};case "Insert":return{ctor:"_Tuple2",_0:db,_1:v(ya,c,f,g,l,h)};default:return{ctor:"_Tuple2",_0:cb,_1:v(Qa,c,f,g,l,h)}}}};c=d(c);var f=c._1;switch(c._0.ctor){case "Same":return f;case "Insert":return Wc(f);default:return Xc(f)}}),X=l(function(a,b,c){return p(eb,
a,Ta(L(b)),c)});f(function(a,b){return p(X,a,b,N)});f(function(a,b){return p(ma,X,b,a)});var Zc=f(function(a,b){var c=l(function(b,c,f){return e(a,b,c)?p(X,b,c,f):f});return p(ma,c,N,b)});f(function(a,b){return e(Zc,f(function(a,d){return e(Rc,a,b)}),a)});f(function(a,b){var c=l(function(b,c,f){var d=f._1;f=f._0;return e(a,b,c)?{ctor:"_Tuple2",_0:p(X,b,c,f),_1:d}:{ctor:"_Tuple2",_0:f,_1:p(X,b,c,d)}});return p(ma,c,{ctor:"_Tuple2",_0:N,_1:N},b)});var $c=f(function(a,b){return p(eb,a,Ta(J),b)});f(function(a,
b){return p(ma,l(function(a,b,f){return e($c,a,f)}),a,b)});var Vb=function(){return{now:x.nativeBinding(function(a){a(x.succeed(Date.now()))}),setInterval_:f(function(a,b){return x.nativeBinding(function(c){var d=setInterval(function(){x.rawSpawn(b)},a);return function(){clearInterval(d)}})})}}(),ad=Vb.setInterval_,Wb=l(function(a,b,c){if("[]"===b.ctor)return A(c);var d=b._0;return e(z,x.spawn(e(ad,d,e(Ab,a,d))),function(e){return p(Wb,a,b._1,p(X,d,e,c))})}),bd=f(function(a,b){var c=a._1;a=a._0;var d=
e(Na,a,b);return"Nothing"===d.ctor?p(X,a,h.fromArray([c]),b):p(X,a,e(y["::"],c,d._0),b)}),cd=Vb.now,dd=l(function(a,b,c){var d=e(Na,b,c.taggers);return"Nothing"===d.ctor?A(c):e(z,cd,function(b){return e(z,La(e(ia,function(c){return e(Za,a,c(b))},d._0)),function(a){return A(c)})})}),ed=U.leaf("Time"),Xb=f(function(a,b){return{taggers:a,processes:b}}),fd=A(e(Xb,N,N)),gd=l(function(a,b,c){var d=l(function(a,b,c){return{ctor:"_Tuple3",_0:c._0,_1:c._1,_2:e(z,x.kill(b),function(a){return c._2})}}),f=w(function(a,
b,c,d){return{ctor:"_Tuple3",_0:d._0,_1:p(X,a,c,d._1),_2:d._2}}),m=l(function(a,b,c){return{ctor:"_Tuple3",_0:e(y["::"],a,c._0),_1:c._1,_2:c._2}}),n=p(sa,bd,N,b);b=ub(Lb,m,f,d,n,c.processes,{ctor:"_Tuple3",_0:h.fromArray([]),_1:N,_2:A({ctor:"_Tuple0"})});var q=b._0,r=b._1;return e(z,b._2,function(b){return e(z,p(Wb,a,q,r),function(a){return A(e(Xb,n,a))})})}),Yb=f(function(a,b){return{ctor:"Every",_0:a,_1:b}});f(function(a,b){return ed(e(Yb,a,b))});var hd=f(function(a,b){return e(Yb,b._0,function(c){return a(b._1(c))})});
U.effectManagers.Time={pkg:"elm-lang/core",init:fd,onEffects:gd,onSelfMsg:dd,tag:"sub",subMap:hd};var P=function(){function a(a,b){return{ctor:"<decoder>",tag:"map-many",func:a,decoders:b}}function b(a,b){return{ctor:"<decoder>",tag:"tuple",func:a,decoders:b}}function c(a){return{tag:"ok",value:a}}function d(a,b){return{tag:"primitive",type:a,value:b}}function e(a,b){return{tag:"index",index:a,rest:b}}function m(a){for(var b="_";a;)switch(a.tag){case "primitive":return b="Expecting "+a.type+("_"===
b?"":" at "+b)+" but instead got: ",a=a.value,a=void 0===a?"undefined":JSON.stringify(a),b+a;case "index":b+="["+a.index+"]";a=a.rest;break;case "field":b+="."+a.field;a=a.rest;break;case "oneOf":a=a.problems;for(var c=0;c<a.length;c++)a[c]=m(a[c]);return"I ran into the following problems"+("_"===b?"":" at "+b)+":\n\n"+a.join("\n");case "custom":return"A `customDecoder` failed"+("_"===b?"":" at "+b)+" with the message: "+a.msg;case "fail":return"I ran into a `fail` decoder"+("_"===b?"":" at "+b)+
": "+a.msg}}function n(a,b){a=p(a,b);return"ok"===a.tag?Z(a.value):B(m(a))}function p(a,b){switch(a.tag){case "bool":return"boolean"===typeof b?c(b):d("a Bool",b);case "int":return"number"!==typeof b?d("an Int",b):-2147483647<b&&2147483647>b&&(b|0)===b||isFinite(b)&&!(b%1)?c(b):d("an Int",b);case "float":return"number"===typeof b?c(b):d("a Float",b);case "string":return"string"===typeof b?c(b):b instanceof String?c(b+""):d("a String",b);case "null":return null===b?c(a.value):d("null",b);case "value":return c(b);
case "list":if(!(b instanceof Array))return d("a List",b);for(var f=h.Nil,k=b.length;k--;){var g=p(a.decoder,b[k]);if("ok"!==g.tag)return e(k,g);f=h.Cons(g.value,f)}return c(f);case "array":if(!(b instanceof Array))return d("an Array",b);for(var f=b.length,l=Array(f),k=f;k--;){g=p(a.decoder,b[k]);if("ok"!==g.tag)return e(k,g);l[k]=g.value}return c(E.fromJSArray(l));case "maybe":return g=p(a.decoder,b),"ok"===g.tag?c(L(g.value)):c(J);case "field":k=a.field;if("object"!==typeof b||null===b||!(k in b))return d("an object with a field named `"+
k+"`",b);g=p(a.decoder,b[k]);return"ok"===g.tag?g:{tag:"field",field:k,rest:g};case "key-value":if("object"!==typeof b||null===b||b instanceof Array)return d("an object",b);k=h.Nil;for(f in b){g=p(a.decoder,b[f]);if("ok"!==g.tag)return{tag:"field",field:f,rest:g};g=q.Tuple2(f,g.value);k=h.Cons(g,k)}return c(k);case "map-many":for(var l=a.func,u=a.decoders,k=0;k<u.length;k++){g=p(u[k],b);if("ok"!==g.tag)return g;l=l(g.value)}return c(l);case "tuple":u=a.decoders;f=u.length;if(!(b instanceof Array)||
b.length!==f)return d("a Tuple with "+f+" entries",b);l=a.func;for(k=0;k<f;k++){g=p(u[k],b[k]);if("ok"!==g.tag)return e(k,g);l=l(g.value)}return c(l);case "customAndThen":g=p(a.decoder,b);if("ok"!==g.tag)return g;b=a.callback(g.value);return"Err"===b.ctor?{tag:"custom",msg:b._0}:c(b._0);case "andThen":return g=p(a.decoder,b),"ok"!==g.tag?g:p(a.callback(g.value),b);case "oneOf":k=[];for(a=a.decoders;"[]"!==a.ctor;){g=p(a._0,b);if("ok"===g.tag)return g;k.push(g);a=a._1}return{tag:"oneOf",problems:k};
case "fail":return{tag:"fail",msg:a.msg};case "succeed":return c(a.msg)}}function r(a,b){if(a===b)return!0;if(a.tag!==b.tag)return!1;switch(a.tag){case "succeed":case "fail":return a.msg===b.msg;case "bool":case "int":case "float":case "string":case "value":return!0;case "null":return a.value===b.value;case "list":case "array":case "maybe":case "key-value":return r(a.decoder,b.decoder);case "field":return a.field===b.field&&r(a.decoder,b.decoder);case "map-many":case "tuple":return a.func!==b.func?
!1:x(a.decoders,b.decoders);case "andThen":case "customAndThen":return a.callback===b.callback&&r(a.decoder,b.decoder);case "oneOf":return x(a.decoders,b.decoders)}}function x(a,b){var c=a.length;if(c!==b.length)return!1;for(var d=0;d<c;d++)if(!r(a[d],b[d]))return!1;return!0}return{encode:f(function(a,b){return JSON.stringify(b,null,a)}),runOnString:f(function(a,b){var c;try{c=JSON.parse(b)}catch(ja){return B("Given an invalid JSON: "+ja.message)}return n(a,c)}),run:f(n),decodeNull:function(a){return{ctor:"<decoder>",
tag:"null",value:a}},decodePrimitive:function(a){return{ctor:"<decoder>",tag:a}},decodeContainer:f(function(a,b){return{ctor:"<decoder>",tag:a,decoder:b}}),decodeField:f(function(a,b){return{ctor:"<decoder>",tag:"field",field:a,decoder:b}}),decodeObject1:f(function(b,c){return a(b,[c])}),decodeObject2:l(function(b,c,d){return a(b,[c,d])}),decodeObject3:w(function(b,c,d,e){return a(b,[c,d,e])}),decodeObject4:D(function(b,c,d,e,f){return a(b,[c,d,e,f])}),decodeObject5:S(function(b,c,d,e,f,g){return a(b,
[c,d,e,f,g])}),decodeObject6:rb(function(b,c,d,e,f,g,u){return a(b,[c,d,e,f,g,u])}),decodeObject7:sb(function(b,c,d,e,f,g,u,t){return a(b,[c,d,e,f,g,u,t])}),decodeObject8:tb(function(b,c,d,e,f,g,u,t,h){return a(b,[c,d,e,f,g,u,t,h])}),decodeKeyValuePairs:function(a){return{ctor:"<decoder>",tag:"key-value",decoder:a}},decodeTuple1:f(function(a,c){return b(a,[c])}),decodeTuple2:l(function(a,c,d){return b(a,[c,d])}),decodeTuple3:w(function(a,c,d,e){return b(a,[c,d,e])}),decodeTuple4:D(function(a,c,d,
e,f){return b(a,[c,d,e,f])}),decodeTuple5:S(function(a,c,d,e,f,g){return b(a,[c,d,e,f,g])}),decodeTuple6:rb(function(a,c,d,e,f,g,u){return b(a,[c,d,e,f,g,u])}),decodeTuple7:sb(function(a,c,d,e,f,g,u,t){return b(a,[c,d,e,f,g,u,t])}),decodeTuple8:tb(function(a,c,d,e,f,g,u,t,h){return b(a,[c,d,e,f,g,u,t,h])}),andThen:f(function(a,b){return{ctor:"<decoder>",tag:"andThen",decoder:a,callback:b}}),customAndThen:f(function(a,b){return{ctor:"<decoder>",tag:"customAndThen",decoder:a,callback:b}}),fail:function(a){return{ctor:"<decoder>",
tag:"fail",msg:a}},succeed:function(a){return{ctor:"<decoder>",tag:"succeed",msg:a}},oneOf:function(a){return{ctor:"<decoder>",tag:"oneOf",decoders:a}},identity:function(a){return a},encodeNull:null,encodeArray:E.toJSArray,encodeList:h.toArray,encodeObject:function(a){for(var b={};"[]"!==a.ctor;){var c=a._0;b[c._0]=c._1;a=a._1}return b},equality:r}}(),id=P.identity,jd=P.identity,fb=P.succeed,zb=P.run;P.decodePrimitive("value");var kd=P.decodePrimitive("bool"),Zb=P.decodePrimitive("int");P.decodePrimitive("float");
var ld=P.decodePrimitive("string"),za=za||{};za[":="]=P.decodeField;var $b=f(function(a,b){return p(fa,f(function(a,b){return e(za[":="],a,b)}),b,a)}),md=x.kill,nd=x.spawn,od=function(){function a(a){return function(b,c,d){return x.nativeBinding(function(f){function g(a){a=e(zb,c,a);"Ok"===a.ctor&&x.rawSpawn(d(a._0))}a.addEventListener(b,g);return function(){a.removeEventListener(b,g)}})}}function b(a,b){return x.nativeBinding(function(d){c(function(){var c=document.getElementById(a);null===c?d(x.fail({ctor:"NotFound",
_0:a})):d(x.succeed(b(c)))})})}var c="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){a()};return{onDocument:l(a(document)),onWindow:l(a(window)),focus:function(a){return b(a,function(a){a.focus();return q.Tuple0})},blur:function(a){return b(a,function(a){a.blur();return q.Tuple0})},getScrollTop:function(a){return b(a,function(a){return a.scrollTop})},setScrollTop:f(function(a,c){return b(a,function(a){a.scrollTop=c;return q.Tuple0})}),getScrollLeft:function(a){return b(a,
function(a){return a.scrollLeft})},setScrollLeft:f(function(a,c){return b(a,function(a){a.scrollLeft=c;return q.Tuple0})}),toBottom:function(a){return b(a,function(a){a.scrollTop=a.scrollHeight;return q.Tuple0})},toRight:function(a){return b(a,function(a){a.scrollLeft=a.scrollWidth;return q.Tuple0})},height:f(function(a,c){return b(c,function(b){switch(a.ctor){case "Content":return b.scrollHeight;case "VisibleContent":return b.clientHeight;case "VisibleContentWithBorders":return b.offsetHeight;case "VisibleContentWithBordersAndMargins":return b=
b.getBoundingClientRect(),b.bottom-b.top}})}),width:f(function(a,c){return b(c,function(b){switch(a.ctor){case "Content":return b.scrollWidth;case "VisibleContent":return b.clientWidth;case "VisibleContentWithBorders":return b.offsetWidth;case "VisibleContentWithBordersAndMargins":return b=b.getBoundingClientRect(),b.right-b.left}})})}}().onDocument,Aa=function(){function a(a,b,c){return{type:"thunk",func:a,args:b,thunk:c,node:void 0}}function b(a){for(var b,c={};"[]"!==a.ctor;){var d=a._0,e=d.key;
if("ATTR"===e||"ATTR_NS"===e||"EVENT"===e){var f=c[e]||{};f[d.realKey]=d.value;c[e]=f}else if("STYLE"===e){f=c[e]||{};for(d=d.value;"[]"!==d.ctor;){var u=d._0;f[u._0]=u._1;d=d._1}c[e]=f}else"namespace"===e?b=d.value:c[e]=d.value;a=a._1}return{facts:c,namespace:b}}function c(a,b,c){function e(){switch(t){case "NO_REQUEST":throw Error("Unexpected draw callback.\nPlease report this to <https://github.com/elm-lang/core/issues>.");case "PENDING_REQUEST":y(e);t="EXTRA_REQUEST";var a=[];n(g,h,a,0);var b=
u;0===a.length?u=b:(x(b,g,a,0,0,g.descendantsCount,f),u=v(b,a));g=h;break;case "EXTRA_REQUEST":t="NO_REQUEST"}}var f={tagger:b,parent:void 0},u=d(c,f);a.appendChild(u);var t="NO_REQUEST",g=c,h=c;return{update:function(a){"NO_REQUEST"===t&&y(e);t="PENDING_REQUEST";h=a}}}function d(a,b){switch(a.type){case "thunk":return a.node||(a.node=a.thunk()),d(a.node,b);case "tagger":var c=a.node;for(a=a.tagger;"tagger"===c.type;)"object"!==typeof a?a=[a,c.tagger]:a.push(c.tagger),c=c.node;b={tagger:a,parent:b};
c=d(c,b);c.elm_event_node_ref=b;return c;case "text":return document.createTextNode(a.text);case "node":c=a.namespace?document.createElementNS(a.namespace,a.tag):document.createElement(a.tag);g(c,b,a.facts);a=a.children;for(var e=0;e<a.length;e++)c.appendChild(d(a[e],b));return c;case "keyed-node":c=a.namespace?document.createElementNS(a.namespace,a.tag):document.createElement(a.tag);g(c,b,a.facts);a=a.children;for(e=0;e<a.length;e++)c.appendChild(d(a[e]._1,b));return c;case "custom":return c=a.impl.render(a.model),
g(c,b,a.facts),c}}function g(a,b,c){for(var d in c){var e=c[d];switch(d){case "STYLE":var f=e,g=a.style,e=void 0;for(e in f)g[e]=f[e];break;case "EVENT":var f=a,g=b,t=f.elm_handlers||{},u=void 0;for(u in e){var k=t[u],l=e[u];"undefined"===typeof l?(f.removeEventListener(u,k),t[u]=void 0):"undefined"===typeof k?(k=h(g,l),f.addEventListener(u,k),t[u]=k):k.info=l}f.elm_handlers=t;break;case "ATTR":f=a;g=e;e=void 0;for(e in g)t=g[e],"undefined"===typeof t?f.removeAttribute(e):f.setAttribute(e,t);break;
case "ATTR_NS":f=a;g=e;e=void 0;for(e in g)u=g[e],t=u.namespace,u=u.value,"undefined"===typeof u?f.removeAttributeNS(t,e):f.setAttributeNS(t,e,u);break;case "value":a[d]!==e&&(a[d]=e);break;default:a[d]=e}}}function h(a,b){function c(b){var d=c.info,f=e(P.run,d.decoder,b);if("Ok"===f.ctor)for(d=d.options,d.stopPropagation&&b.stopPropagation(),d.preventDefault&&b.preventDefault(),b=f._0,f=a;f;){d=f.tagger;if("function"===typeof d)b=d(b);else for(var g=d.length;g--;)b=d[g](b);f=f.parent}}c.info=b;return c}
function m(a,b,c){return{index:b,type:a,data:c,domNode:void 0,eventNode:void 0}}function n(a,b,c,d){if(a!==b){var e=b.type;if(a.type!==e)c.push(m("p-redraw",d,b));else switch(e){case "thunk":for(var f=a.args,g=b.args,h=f.length,t=a.func===b.func&&h===g.length;t&&h--;)t=f[h]===g[h];if(t){b.node=a.node;break}b.node=b.thunk();f=[];n(a.node,b.node,f,0);0<f.length&&c.push(m("p-thunk",d,f));break;case "tagger":for(var t=a.tagger,f=b.tagger,u=!1,g=a.node;"tagger"===g.type;)u=!0,"object"!==typeof t?t=[t,
g.tagger]:t.push(g.tagger),g=g.node;for(h=b.node;"tagger"===h.type;)u=!0,"object"!==typeof f?f=[f,h.tagger]:f.push(h.tagger),h=h.node;if(u&&t.length!==f.length){c.push(m("p-redraw",d,b));break}if(u){a:{for(u=0;u<t.length;u++)if(t[u]!==f[u]){t=!1;break a}t=!0}t=!t}else t=t!==f;t&&c.push(m("p-tagger",d,f));n(g,h,c,d+1);break;case "text":a.text!==b.text&&c.push(m("p-text",d,b.text));break;case "node":if(a.tag!==b.tag||a.namespace!==b.namespace){c.push(m("p-redraw",d,b));break}e=q(a.facts,b.facts);"undefined"!==
typeof e&&c.push(m("p-facts",d,e));f=a.children;g=b.children;h=f.length;t=g.length;h>t?c.push(m("p-remove-last",d,h-t)):h<t&&c.push(m("p-append",d,g.slice(h)));h=h<t?h:t;for(t=0;t<h;t++)d++,u=f[t],n(u,g[t],c,d),d+=u.descendantsCount||0;break;case "keyed-node":if(a.tag!==b.tag||a.namespace!==b.namespace){c.push(m("p-redraw",d,b));break}e=q(a.facts,b.facts);"undefined"!==typeof e&&c.push(m("p-facts",d,e));var e=[],l={},C=[];a=a.children;b=b.children;for(var R=a.length,p=b.length,w=0,x=0,v=d;w<R&&x<
p;){var y=a[w],z=b[x],B=y._0,H=z._0,A=y._1,y=z._1;if(B===H)v++,n(A,y,e,v),v+=A.descendantsCount||0,w++,x++;else{var z=w+1<R,E=x+1<p;z&&(t=a[w+1],f=t._0,t=t._1,u=H===f);if(E)var D=b[x+1],g=D._0,D=D._1,G=B===g;if(z&&E&&G&&u)v++,n(A,D,e,v),r(l,e,B,y,x,C),v+=A.descendantsCount||0,v++,k(l,e,B,t,v),v+=t.descendantsCount||0,w+=2,x+=2;else if(E&&G)v++,r(l,e,H,y,x,C),n(A,D,e,v),v+=A.descendantsCount||0,w+=1,x+=2;else if(z&&u)v++,k(l,e,B,A,v),v+=A.descendantsCount||0,v++,n(t,y,e,v),v+=t.descendantsCount||0,
w+=2,x+=1;else if(z&&E&&f===g)v++,k(l,e,B,A,v),r(l,e,H,y,x,C),v+=A.descendantsCount||0,v++,n(t,D,e,v),v+=t.descendantsCount||0,w+=2,x+=2;else break}}for(;w<R;)v++,y=a[w],A=y._1,k(l,e,y._0,A,v),v+=A.descendantsCount||0,w++;for(;x<p;)h=h||[],z=b[x],r(l,e,z._0,z._1,void 0,h),x++;(0<e.length||0<C.length||"undefined"!==typeof h)&&c.push(m("p-reorder",d,{patches:e,inserts:C,endInserts:h}));break;case "custom":a.impl!==b.impl?c.push(m("p-redraw",d,b)):(e=q(a.facts,b.facts),"undefined"!==typeof e&&c.push(m("p-facts",
d,e)),(f=b.impl.diff(a,b))&&c.push(m("p-custom",d,f)))}}}function q(a,b,c){var d,e;for(e in a)if("STYLE"===e||"EVENT"===e||"ATTR"===e||"ATTR_NS"===e){var f=q(a[e],b[e]||{},e);f&&(d=d||{},d[e]=f)}else if(e in b){var f=a[e],g=b[e],h;!(h=f===g&&"value"!==e)&&(h="EVENT"===c)&&(h=!f.options!==g.options||f.stopPropagation===g.stopPropagation&&f.preventDefault===g.preventDefault?P.equality(f.decoder,g.decoder):!1);h||(d=d||{},d[e]=g)}else d=d||{},d[e]="undefined"===typeof c?"string"===typeof a[e]?"":null:
"STYLE"===c?"":"EVENT"===c||"ATTR"===c?void 0:{namespace:a[e].namespace,value:void 0};for(var t in b)t in a||(d=d||{},d[t]=b[t]);return d}function r(a,b,c,d,e,f){var g=a[c];"undefined"===typeof g?(g={tag:"insert",vnode:d,index:e,data:void 0},f.push({index:e,entry:g}),a[c]=g):"remove"===g.tag?(f.push({index:e,entry:g}),g.tag="move",a=[],n(g.vnode,d,a,g.index),g.index=e,g.data.data={patches:a,entry:g}):r(a,b,c+B,d,e,f)}function k(a,b,c,d,e){var f=a[c];"undefined"===typeof f?(f=m("p-remove",e,void 0),
b.push(f),a[c]={tag:"remove",vnode:d,index:e,data:f}):"insert"===f.tag?(f.tag="move",a=[],n(d,f.vnode,a,e),f=m("p-remove",e,{patches:a,entry:f}),b.push(f)):k(a,b,c+B,d,e)}function x(a,b,c,d,e,f,g){for(var h=c[d],t=h.index;t===e;){var k=h.type;"p-thunk"===k?(k=b.node,x(a,k,h.data,0,0,k.descendantsCount,g)):"p-reorder"===k?(h.domNode=a,h.eventNode=g,k=h.data.patches,0<k.length&&x(a,b,k,0,e,f,g)):"p-remove"===k?(h.domNode=a,h.eventNode=g,k=h.data,"undefined"!==typeof k&&(k.entry.data=a,k=k.patches,0<
k.length&&x(a,b,k,0,e,f,g))):(h.domNode=a,h.eventNode=g);d++;if(!(h=c[d])||(t=h.index)>f)return d}switch(b.type){case "tagger":for(g=b.node;"tagger"===g.type;)g=g.node;return x(a,g,c,d,e+1,f,a.elm_event_node_ref);case "node":b=b.children;a=a.childNodes;for(k=0;k<b.length;k++){e++;var l=b[k],u=e+(l.descendantsCount||0);if(e<=t&&t<=u&&(d=x(a[k],l,c,d,e,u,g),!(h=c[d])||(t=h.index)>f))break;e=u}return d;case "keyed-node":b=b.children;a=a.childNodes;for(k=0;k<b.length;k++){e++;l=b[k]._1;u=e+(l.descendantsCount||
0);if(e<=t&&t<=u&&(d=x(a[k],l,c,d,e,u,g),!(h=c[d])||(t=h.index)>f))break;e=u}return d;case "text":case "thunk":throw Error("should never traverse `text` or `thunk` nodes like this");}}function v(a,b){for(var c=0;c<b.length;c++){var d=b[c],e=d.domNode,d=z(e,d);e===a&&(a=d)}return a}function z(a,b){switch(b.type){case "p-redraw":var c=a.parentNode;b=d(b.data,b.eventNode);"undefined"===typeof b.elm_event_node_ref&&(b.elm_event_node_ref=a.elm_event_node_ref);c&&b!==a&&c.replaceChild(b,a);return b;case "p-facts":return g(a,
b.eventNode,b.data),a;case "p-text":return a.replaceData(0,a.length,b.data),a;case "p-thunk":return v(a,b.data);case "p-tagger":return a.elm_event_node_ref.tagger=b.data,a;case "p-remove-last":for(c=b.data;c--;)a.removeChild(a.lastChild);return a;case "p-append":for(var e=b.data,c=0;c<e.length;c++)a.appendChild(d(e[c],b.eventNode));return a;case "p-remove":b=b.data;if("undefined"===typeof b)return a.parentNode.removeChild(a),a;c=b.entry;"undefined"!==typeof c.index&&a.parentNode.removeChild(a);c.data=
v(a,b.patches);return a;case "p-reorder":e=b.data;c=e.endInserts;if("undefined"!==typeof c){for(var f=document.createDocumentFragment(),h=0;h<c.length;h++){var k=c[h].entry;f.appendChild("move"===k.tag?k.data:d(k.vnode,b.eventNode))}c=f}else c=void 0;a=v(a,e.patches);e=e.inserts;for(f=0;f<e.length;f++)h=e[f],k=h.entry,k="move"===k.tag?k.data:d(k.vnode,b.eventNode),a.insertBefore(k,a.childNodes[h.index]);"undefined"!==typeof c&&a.appendChild(c);return a;case "p-custom":return b=b.data,b.applyPatch(a,
b.data);default:throw Error("Ran into an unknown patch!");}}var y="undefined"!==typeof requestAnimationFrame?requestAnimationFrame:function(a){setTimeout(a,1E3/60)},B="_elmW6BL";return{node:function(a){return f(function(c,d){var e=b(c);c=e.namespace;for(var e=e.facts,f=[],g=0;"[]"!==d.ctor;){var h=d._0,g=g+(h.descendantsCount||0);f.push(h);d=d._1}g+=f.length;return{type:"node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}})},text:function(a){return{type:"text",text:a}},custom:function(a,
c,d){return{type:"custom",facts:b(a).facts,model:c,impl:d}},map:f(function(a,b){return{type:"tagger",tagger:a,node:b,descendantsCount:1+(b.descendantsCount||0)}}),on:l(function(a,b,c){return{key:"EVENT",realKey:a,value:{options:b,decoder:c}}}),style:function(a){return{key:"STYLE",value:a}},property:f(function(a,b){return{key:a,value:b}}),attribute:f(function(a,b){return{key:"ATTR",realKey:a,value:b}}),attributeNS:l(function(a,b,c){return{key:"ATTR_NS",realKey:b,value:{value:c,namespace:a}}}),lazy:f(function(b,
c){return a(b,[c],function(){return b(c)})}),lazy2:l(function(b,c,d){return a(b,[c,d],function(){return e(b,c,d)})}),lazy3:w(function(b,c,d,e){return a(b,[c,d,e],function(){return p(b,c,d,e)})}),keyedNode:l(function(a,c,d){var e=b(c);c=e.namespace;for(var e=e.facts,f=[],g=0;"[]"!==d.ctor;){var h=d._0,g=g+(h._1.descendantsCount||0);f.push(h);d=d._1}g+=f.length;return{type:"keyed-node",tag:a,facts:e,children:f,namespace:c,descendantsCount:g}}),programWithFlags:function(a){return{init:a.init,update:a.update,
subscriptions:a.subscriptions,view:a.view,renderer:c}}}}(),ua=Aa.programWithFlags,ac={stopPropagation:!1,preventDefault:!1},pd=Aa.on,gb=f(function(a,b){return p(pd,a,ac,b)}),bc=Aa.property,Ba=Aa.text,m=Aa.node;f(function(a,b){return{stopPropagation:a,preventDefault:b}});m("body");m("section");m("nav");m("article");m("aside");var qd=m("h1");m("h2");m("h3");m("h4");m("h5");m("h6");m("header");m("footer");m("address");m("main");m("p");m("hr");m("pre");m("blockquote");m("ol");var cc=m("ul"),rd=m("li");
m("dl");m("dt");m("dd");m("figure");m("figcaption");var Y=m("div");m("a");m("em");m("strong");m("small");m("s");m("cite");m("q");m("dfn");m("abbr");m("time");m("code");m("var");m("samp");m("kbd");m("sub");m("sup");m("i");m("b");m("u");m("mark");m("ruby");m("rt");m("rp");m("bdi");m("bdo");var hb=m("span");m("br");m("wbr");m("ins");m("del");m("img");m("iframe");m("embed");m("object");m("param");m("video");m("audio");m("source");m("track");m("canvas");m("svg");m("math");m("table");m("caption");m("colgroup");
m("col");m("tbody");m("thead");m("tfoot");m("tr");m("td");m("th");m("form");m("fieldset");m("legend");m("label");m("input");m("button");m("select");m("datalist");m("optgroup");m("option");m("textarea");m("keygen");m("output");m("progress");m("meter");m("details");m("summary");m("menuitem");m("menu");var sd=ua,td=f(function(a,b){return e(bc,a,jd(b))}),O=function(a){return e(td,"className",a)};f(function(a,b){return e(bc,a,id(b))});e(za[":="],"keyCode",Zb);e($b,h.fromArray(["target","checked"]),kd);
e($b,h.fromArray(["target","value"]),ld);q.update(ac,{preventDefault:!0});f(function(a,b){return{stopPropagation:a,preventDefault:b}});var ud=l(function(a,b,c){var d=e(Na,b.category,c);return"Nothing"===d.ctor?A(c):e(z,La(e(ia,function(c){return e(Za,a,c(b.keyCode))},d._0.taggers)),function(a){return A(c)})}),ib=ib||{};ib["&>"]=f(function(a,b){return e(z,a,function(a){return b})});var vd=A(N),wd=f(function(a,b){return"Nothing"===b.ctor?L(h.fromArray([a])):L(e(y["::"],a,b._0))}),xd=f(function(a,b){for(;;){var c=
a;if("[]"===c.ctor)return b;a=c._1;b=p(eb,c._0._0,wd(c._0._1),b)}}),yd=e(za[":="],"keyCode",Zb),zd=U.leaf("Keyboard"),dc=f(function(a,b){return{taggers:a,pid:b}}),Ad=f(function(a,b){return{category:a,keyCode:b}}),Bd=l(function(a,b,c){var d=l(function(b,c,d){return e(z,d,function(d){return e(z,nd(p(od,b,yd,function(c){return e(Ab,a,e(Ad,b,c))})),function(a){return A(p(X,b,e(dc,c,a),d))})})}),f=w(function(a,b,c,d){return e(z,d,function(d){return A(p(X,a,e(dc,c,b.pid),d))})}),h=l(function(a,b,c){return e(ib["&>"],
md(b.pid),c)});return ub(Lb,h,f,d,c,e(xd,b,N),A(N))}),ec=f(function(a,b){return{ctor:"MySub",_0:a,_1:b}}),Cd=f(function(a,b){return e(ec,b._0,function(c){return a(b._1(c))})});U.effectManagers.Keyboard={pkg:"elm-lang/keyboard",init:vd,onEffects:Bd,onSelfMsg:ud,tag:"sub",subMap:Cd};D(function(a,b,c,d,e){return{name:a,displayName:b,role:c,strongCounters:d,weakCounters:e}});var oa={ctor:"Offense"},jb={name:"genji",displayName:"Genji",role:oa,strongCounters:h.fromArray(["bastion","mercy","torbjorn"]),
weakCounters:h.fromArray(["mei","zarya","winston"])},kb={name:"mccree",displayName:"McCree",role:oa,strongCounters:h.fromArray(["reaper","tracer","winston"]),weakCounters:h.fromArray(["genji","soldier76","widowmaker"])},Dd={name:"pharah",displayName:"Pharah",role:oa,strongCounters:h.fromArray(["bastion","junkrat","mei"]),weakCounters:h.fromArray(["mccree","roadhog","soldier76"])},Ed={name:"reaper",displayName:"Reaper",role:oa,strongCounters:h.fromArray(["bastion","mei","winston"]),weakCounters:h.fromArray(["junkrat",
"mccree","pharah"])},Fd={name:"soldier76",displayName:"Soldier: 76",role:oa,strongCounters:h.fromArray(["mercy","pharah","torbjorn"]),weakCounters:h.fromArray(["genji","mei","tracer"])},Gd={name:"tracer",displayName:"Tracer",role:oa,strongCounters:h.fromArray(["bastion","mercy","widowmaker"]),weakCounters:h.fromArray(["mccree","mei","soldier76"])},pa={ctor:"Defense"},Hd={name:"bastion",displayName:"Bastion",role:pa,strongCounters:h.fromArray(["mercy","reinhardt","winston"]),weakCounters:h.fromArray(["genji",
"tracer","widowmaker"])},fc={name:"hanzo",displayName:"Hanzo",role:pa,strongCounters:h.fromArray(["bastion","torbjorn","widowmaker"]),weakCounters:h.fromArray(["dva","tracer","widowmaker"])},Id={name:"junkrat",displayName:"Junkrat",role:pa,strongCounters:h.fromArray(["bastion","mei","torbjorn"]),weakCounters:h.fromArray(["mccree","pharah","widowmaker"])},Jd={name:"mei",displayName:"Mei",role:pa,strongCounters:h.fromArray(["genji","winston","tracer"]),weakCounters:h.fromArray(["junkrat","pharah","widowmaker"])},
Kd={name:"torbjorn",displayName:"Torbj\u00f6rn",role:pa,strongCounters:h.fromArray(["genji","lucio","tracer"]),weakCounters:h.fromArray(["junkrat","pharah","widowmaker"])},Ld={name:"widowmaker",displayName:"Widowmaker",role:pa,strongCounters:h.fromArray(["bastion","torbjorn","pharah"]),weakCounters:h.fromArray(["dva","genji","winston"])},Ca={ctor:"Tank"},Md={name:"dva",displayName:"D.Va",role:Ca,strongCounters:h.fromArray(["pharah","reinhardt","windowmaker"]),weakCounters:h.fromArray(["mei","zarya",
"winston"])},lb={name:"reinhardt",displayName:"Reinhardt",role:Ca,strongCounters:h.fromArray(["soldier76","torbjorn","widowmaker"]),weakCounters:h.fromArray(["reaper","roadhog","symmetra"])},mb={name:"roadhog",displayName:"Roadhog",role:Ca,strongCounters:h.fromArray(["pharah","reinhardt","tracer"]),weakCounters:h.fromArray(["dva","genji","reaper"])},Nd={name:"winston",displayName:"Winston",role:Ca,strongCounters:h.fromArray(["genji","hanzo","widowmaker"]),weakCounters:h.fromArray(["mccree","mei",
"reaper"])},Od={name:"zarya",displayName:"Zarya",role:Ca,strongCounters:h.fromArray(["dva","genji","winston"]),weakCounters:h.fromArray(["pharah","roadhog","reaper"])},Da={ctor:"Support"},Pd={name:"ana",displayName:"Ana",role:Da,strongCounters:h.fromArray(["lucio","mercy","zenyatta"]),weakCounters:h.fromArray(["genji","reaper","tracer"])},nb={name:"lucio",displayName:"Lucio",role:Da,strongCounters:h.fromArray(["dva","reaper","winston"]),weakCounters:h.fromArray(["mei","mccree","pharah"])},Qd={name:"mercy",
displayName:"Mercy",role:Da,strongCounters:h.fromArray([]),weakCounters:h.fromArray(["mccree","tracer","widowmaker"])},Rd={name:"symmetra",displayName:"Symmetra",role:Da,strongCounters:h.fromArray(["bastion","dva","reinhardt"]),weakCounters:h.fromArray(["junkrat","pharah","roadhog"])},ob={name:"zenyatta",displayName:"Zenyatta",role:Da,strongCounters:h.fromArray(["dva","roadhog","winston"]),weakCounters:h.fromArray(["hanzo","tracer","widowmaker"])},gc=h.fromArray([Pd,Hd,Md,jb,fc,Id,nb,kb,Jd,Qd,Dd,
Ed,lb,mb,Fd,Rd,Kd,Gd,Ld,Nd,Od,ob]),Sd=f(function(a,b){return e(la,function(b){return q.eq(b,a.name)},b.weakCounters)}),Td=f(function(a,b){return e(la,function(b){return q.eq(b,a.name)},b.strongCounters)}),pb=f(function(a,b){return e(Sd,a,b)||e(Td,b,a)}),hc=f(function(a,b){return e(pb,b,a)}),Ud=f(function(a,b){return e(la,hc(b),ha(a))}),Vd=function(a){return function(b){return qa(e(Ud,a,b))}},Wd=f(function(a,b){return e(Fa,Vd(a),ha(b))}),ic=f(function(a,b){return e(Fa,hc(a),ha(b))}),jc=f(function(a,
b){return e(Fa,pb(a),ha(b))}),Xd=l(function(a,b,c){b=e(la,pb(a),e(Wd,b,c))?1:0;var d=Ua(e(ic,a,c));a=Ua(e(jc,a,c));return d-a-b}),Yd=f(function(a,b){var c=ha(a),d=e(Fa,function(a){return qa(e(rc,a,c))},gc),d=e(ia,function(c){return{hero:c,score:p(Xd,c,a,b)}},d),d=sc(e(pc,function(a){return a.score},d));return"Nothing"===d.ctor?fc:d._0.hero}),Zd={ctor:"Enemy"},$d={ctor:"Ally"},ae=f(function(a,b){var c=ia(function(a){return e(rd,h.fromArray([]),h.fromArray([Ba(a.displayName)]))}),d=e(ic,b,a);a=e(jc,
b,a);return e(Y,h.fromArray([]),h.fromArray([e(cc,h.fromArray([O("strength")]),c(a)),e(cc,h.fromArray([O("weakness")]),c(d))]))}),kc=function(a){return e(r["++"],"portrait ",e(r["++"],a.name,e(r["++"]," ",ea(a.role))))},be=f(function(a,b){switch(a.ctor){case "ChangeHero":return q.update(b,{changeHero:L({team:a._0,i:a._1})});case "SetHero":var c=a._1,d=a._2;return"Ally"===a._0.ctor?q.update(b,{changeHero:J,ally:p(Ha,c,d,b.ally)}):q.update(b,{changeHero:J,enemy:p(Ha,c,d,b.enemy)});case "SetAuto":return a=
a._0,q.update(b,{changeHero:J,ally:p(Ha,a,e(Yd,e(Fc,a,b.ally),b.enemy),b.ally)});default:return q.eq(a._0,27)?q.update(b,{changeHero:J}):b}}),ce=f(function(a,b){return{ctor:"_Tuple2",_0:e(be,a,b),_1:Cb}}),de={ctor:"_Tuple2",_0:{enemy:$a(h.fromArray([kb,mb,nb,jb,lb,ob])),ally:$a(h.fromArray([kb,mb,nb,jb,lb,ob])),changeHero:J},_1:Cb};f(function(a,b){return{team:a,i:b}});l(function(a,b,c){return{enemy:a,ally:b,changeHero:c}});var ee=function(a){return{ctor:"KeyPress",_0:a}},fe=l(function(a,b,c){return{ctor:"SetHero",
_0:a,_1:b,_2:c}}),ge=l(function(a,b,c){return e(Y,h.fromArray([e(gb,"click",fb(p(fe,a,b,c))),O(e(r["++"],"hero small ",kc(c)))]),h.fromArray([e(hb,h.fromArray([O("name")]),h.fromArray([Ba(c.displayName)]))]))}),he=l(function(a,b,c){if("Nothing"===c.ctor)return h.fromArray([]);b=c._0;a=e(ia,e(ge,b.team,b.i),a);a="Ally"===b.team.ctor?h.fromArray([e(Y,h.fromArray([O("selector-inner")]),e(r["++"],a,h.fromArray([e(Y,h.fromArray([e(gb,"click",fb({ctor:"SetAuto",_0:b.i})),O("hero small auto")]),h.fromArray([e(hb,
h.fromArray([O("name")]),h.fromArray([Ba("Best Counter")]))]))])))]):h.fromArray([e(Y,h.fromArray([O("selector-inner")]),a)]);return h.fromArray([e(Y,h.fromArray([O("selector")]),a)])}),ie=f(function(a,b){return{ctor:"ChangeHero",_0:a,_1:b}}),je=w(function(a,b,c,d){return e(Y,h.fromArray([e(gb,"click",fb(e(ie,a,c))),O("hero")]),h.fromArray([e(Y,h.fromArray([O(kc(d))]),h.fromArray([e(hb,h.fromArray([O("name")]),h.fromArray([Ba(d.displayName)]))])),e(ae,b,d)]))}),lc=l(function(a,b,c){return h.fromArray([e(qd,
h.fromArray([]),h.fromArray([Ba("Ally"===a.ctor?"Ally Team":"Enemy Team")])),e(Y,h.fromArray([O("team")]),ha(e(Ia,e(je,a,b),c)))])}),mc={main:function(a){return sd(q.update(a,{init:function(b){return a.init}}))}({init:de,view:function(a){var b=p(he,gc,a.enemy,a.changeHero),c=p(lc,$d,a.enemy,a.ally);a=p(lc,Zd,$a(h.fromArray([])),a.enemy);return e(Y,h.fromArray([]),e(r["++"],h.fromArray([e(Y,h.fromArray([O("teams")]),e(r["++"],a,c))]),b))},update:ce,subscriptions:function(a){return zd(e(ec,"keydown",
ee))}})},da={};da.Main=da.Main||{};U.addPublicModule(da.Main,"Main","undefined"===typeof mc?null:mc);n.hot&&function(a){function b(a,c){var d=[],e;for(e in a){var f=a[e],g=c?c+"."+e:e;"fullscreen"in f?d.push({path:g,module:f}):d=d.concat(b(f,g))}return d}function c(b){b=b.split(".");for(var c=a,d=0;d<b.length;++d){var e=b[d];e in c&&(c=c[e]);if(!c)return null}return c}function d(a,b,c,d){var e=++p;return m[e]={id:e,path:c,domNode:a,flags:b,portSubscribes:d,elmProxy:null}}function e(a,b){var c=b.embed,
e=b.fullscreen;b.embed=function(b,e){var f={};q=d(b,e,a,f);b=c(b,e);h(b,f);b=q.elmProxy={ports:b.ports};q=null;return b};b.fullscreen=function(b){var c={};q=d(document.body,b,a,c);b=e(b);h(b,c);b=q.elmProxy={ports:b.ports};q=null;return b}}function f(a){console.log("[elm-hot] Hot-swapping module: "+a.path);r=a;for(var b=a.domNode;b.lastChild;)b.removeChild(b.lastChild);var d=c(a.path),e;d?(e=a.isFullscreen?d.fullscreen(a.flags):d.embed(b,a.flags),a.elmProxy.ports=e.ports,Object.keys(a.portSubscribes).forEach(function(b){if(b in
e.ports&&"subscribe"in e.ports[b]){var c=a.portSubscribes[b];c.length&&(console.log("[elm-hot] Reconnect "+c.length+" handler(s) to port '"+b+"' ("+a.path+")."),c.forEach(function(a){e.ports[b].subscribe(a)}))}else delete a.portSubscribes[b],console.log("[elm-hot] Port was removed: "+b)})):console.log("[elm-hot] Module was removed: "+a.path);r=null}function h(a,b){var c=Object.keys(a.ports||{});c.length&&c.filter(function(b){return"subscribe"in a.ports[b]}).forEach(function(c){var d=a.ports[c],e=
d.subscribe,f=d.unsubscribe;a.ports[c]=Object.assign(d,{subscribe:function(a){console.log("[elm-hot] ports."+c+".subscribe called.");b[c]?b[c].push(a):b[c]=[a];return e.call(d,a)},unsubscribe:function(a){console.log("[elm-hot] ports."+c+".unsubscribe called.");var e=b[c];e&&-1!==e.indexOf(a)?e.splice(e.lastIndexOf(a),1):console.warn("[elm-hot] ports."+c+".unsubscribe: handler not subscribed");return f.call(d,a)}})});return b}"function"!=typeof Object.assign&&(Object.assign=function(a){if(null==a)throw new TypeError("Cannot convert undefined or null to object");
a=Object(a);for(var b=1;b<arguments.length;b++){var c=arguments[b];if(null!=c)for(var d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a});var l;try{l=ua}catch(t){console.warn("[elm-hot] Hot-swapping disabled because VirtualDom module was not found.");return}var m=n.hot.data?n.hot.data.instances||{}:{},p=n.hot.data?n.hot.uid||0:0,k=[],q=null,r=null;n.hot.accept();n.hot.dispose(function(a){a.instances=m;a.uid=p;x.nativeBinding=function(){return x.fail(Error("[elm-hot] Inactive Elm instance."))};
if(k.length){console.log("[elm-hot] Killing "+k.length+" running processes...");try{k.forEach(function(a){a()})}catch(R){console.warn("[elm-hot] Kill process error: "+R.message)}}});ua=function(){var a=q,b=r,c=!!r,d=l.apply(this,arguments),e=d.init,f=d.view;d.init=function(){var a=e.apply(this,arguments);b&&(a._0=b.lastState);return a};d.view=function(d){var e;if(c){c=!1;try{e=f(d)}catch(Ya){throw Error("[elm-hot] Hot-swapping is not possible, please reload page.");}}else e=f(d);a?a.lastState=d:a=
b;return e};return d};var v=x.nativeBinding;x.nativeBinding=function(){var a=v.apply(this,arguments),b=a.callback;a.callback=function(){var a=b.apply(this,arguments);return a?(k.push(a),function(){k.splice(k.indexOf(a),1);return a()}):a};return a};var w=[],y;for(y in m){var u=m[y];u.domNode.parentNode?f(u):w.push(y)}w.forEach(function(a){delete u[a]});b(a).forEach(function(a){e(a.path,a.module)})}(da);if("function"===typeof define&&define.amd)define([],function(){return da});else if("object"===typeof n)n.exports=
da;else{var qb=this.Elm;if("undefined"===typeof qb)this.Elm=da;else for(var Sa in da){if(Sa in qb)throw Error("There are two Elm modules called `"+Sa+"` on this page! Rename one of them.");qb[Sa]=da[Sa]}}}).call(this)}]);
